#!/usr/bin/env python3
"""Batch 2: accounting, advertising, beauty, chemical"""
import json, os, uuid

CONFIGS_DIR = os.path.join(os.path.dirname(__file__), '..', 'saved-configs')

def gen(fn, d):
    steps = []
    for i, s in enumerate(d["steps"], 1):
        st = {"stepIndex": i, "stepName": s["sn"], "serviceName": s["sv"], "description": s["d"],
              "category": s["c"], "estimatedDuration": s["dur"], "businessRationale": s["r"],
              "substeps": [{"substepName": n, "duration": dur} for n, dur in s["sub"]]}
        if i == 1: st["timestamp"] = "2025-11-21T00:00:00.000Z"
        steps.append(st)
    config = {"companyName": d["co"], "domain": d["dom"], "industryType": d["ind"],
              "journeyType": d["jt"], "journeyDetail": d["jd"],
              "journeyId": f"journey_{d['jt'].lower().replace(' ','_')}_{uuid.uuid4().hex[:8]}",
              "journeyStartTime": "2025-11-21T00:00:00.000Z", "steps": steps,
              "id": str(uuid.uuid4()), "name": f"{d['ind']} - {d['jt']}",
              "timestamp": "2026-03-18T12:00:00.000Z", "source": "sector-demo",
              "additionalFields": d["af"]}
    with open(os.path.join(CONFIGS_DIR, fn), 'w') as f: json.dump(config, f, indent=4)
    print(f"  ✅ {fn}")

SECTORS = {
"config-accounting-audit-analytics.json": {
    "co": "AuditTech Global", "dom": "https://www.audittech-global.com",
    "ind": "Accounting & Audit", "jt": "Audit Analytics",
    "jd": "AI-Powered Audit Engagement Workflow",
    "steps": [
        {"sn": "ClientOnboarding", "sv": "ClientOnboardingService", "c": "Intake", "dur": 8,
         "d": "Client entity data, prior year financials, and chart of accounts ingested. AI performs preliminary risk assessment and maps entity structure for multi-entity audits.",
         "r": "Thorough onboarding reduces audit adjustment rate by 30%. Entity mapping errors cause scope gaps and missed risks.",
         "sub": [("EntityMapping", 3), ("FinancialIngestion", 3), ("RiskProfiling", 2)]},
        {"sn": "RiskAssessment", "sv": "RiskAssessmentService", "c": "Analysis", "dur": 16,
         "d": "AI identifies high-risk accounts, unusual transactions, and potential fraud indicators. Materiality thresholds calculated. Audit plan tailored to assessed risks.",
         "r": "Risk-based auditing focuses 80% of effort on the 20% of accounts with highest risk. Reduces audit hours by 15-25%.",
         "sub": [("MaterialityCalculation", 4), ("TransactionAnalysis", 8), ("FraudScreening", 4)]},
        {"sn": "SubstantiveTesting", "sv": "TestingService", "c": "Testing", "dur": 48,
         "d": "AI-selected sample testing of journal entries, vendor payments, revenue recognition, and account reconciliations. Full population analysis on key risk areas.",
         "r": "AI sampling is statistically superior to random selection. Full population testing on high-risk areas catches 95% more anomalies.",
         "sub": [("JournalEntryTesting", 16), ("RevenueVerification", 16), ("ReconciliationReview", 16)]},
        {"sn": "AnalyticalProcedures", "sv": "AnalyticsService", "c": "Analysis", "dur": 24,
         "d": "AI performs ratio analysis, trend analysis, and peer benchmarking. Outliers flagged for investigation. Predictive models compare expected vs actual account balances.",
         "r": "Analytical procedures identify 40% of material misstatements. AI analytics process millions of transactions vs manual sampling of hundreds.",
         "sub": [("RatioAnalysis", 8), ("TrendDetection", 8), ("PeerBenchmarking", 8)]},
        {"sn": "FindingsReview", "sv": "FindingsService", "c": "Review", "dur": 12,
         "d": "AI consolidates findings, calculates aggregate misstatement impact, and drafts management letter points. Partner review workflow with AI-suggested opinion modifications.",
         "r": "Consolidated findings view reduces partner review time by 40%. Missing a material finding in review risks audit failure.",
         "sub": [("FindingsConsolidation", 4), ("MisstatementAggregation", 4), ("OpinionDrafting", 4)]},
        {"sn": "ReportIssuance", "sv": "ReportService", "c": "Delivery", "dur": 8,
         "d": "Audit report, management letter, and tax provision review generated. Digital delivery with e-signature workflow. Archival and regulatory filing automated.",
         "r": "Timely report issuance meets regulatory deadlines. Late filing penalties average $25K-100K for public companies.",
         "sub": [("ReportGeneration", 3), ("PartnerSignoff", 3), ("RegulatoryFiling", 2)]}
    ],
    "af": {
        "orderTotal": 85000, "transactionValue": 85000, "averageOrderValue": 72000,
        "contractValue": 250000, "annualRevenue": 12000000, "revenuePerCustomer": 120000,
        "profitMargin": 28.0, "customerLifetimeValue": 1200000, "lifetimeValue": 1200000,
        "acquisitionCost": 15000, "costPerAcquisition": 15000, "conversionProbability": 0.45,
        "conversionRate": 45, "engagementScore": 72, "timeToConversion": 2160,
        "sessionDuration": 2400, "pageViews": 18, "purchaseFrequency": 1,
        "netPromoterScore": 38, "satisfactionRating": 3.9, "retentionProbability": 0.88,
        "processingTime": 5760, "operationalCost": 45000, "efficiencyRating": 74,
        "auditHours": 1200, "adjustmentRate": 3.5,
        "channel": ["client_portal", "engagement_platform", "email", "video_conf", "in_person"],
        "deviceType": ["desktop", "desktop", "desktop", "desktop", "tablet"],
        "region": ["New York", "London", "Singapore", "Sydney", "Frankfurt"],
        "customerSegmentValue": ["public_company", "private_enterprise", "government", "nonprofit", "SME"],
        "loyaltyTier": ["Strategic", "Key", "Growth", "Standard", "New"],
        "segment": ["financial_audit", "compliance_audit", "internal_audit", "forensic", "IT_audit"],
        "Productname": ["SOX Compliance Audit", "Annual Financial Audit", "Internal Controls Review", "Forensic Investigation", "IT Systems Audit"],
        "ProductId": ["AUD-SOX-001", "AUD-FIN-002", "AUD-IC-003", "AUD-FOR-004", "AUD-IT-005"],
        "ProductType": ["statutory_audit", "financial_audit", "advisory", "forensic", "IT_audit"],
        "Price": [250000, 180000, 95000, 350000, 120000],
        "materialityThreshold": [500000, 250000, 100000, 50000, 75000],
        "riskLevel": ["high", "medium", "low", "critical", "medium"],
        "marketTrend": ["continuous_auditing", "AI_audit_analytics", "real_time_assurance", "blockchain_audit", "ESG_assurance"]
    }
},
"config-accounting-tax-planning.json": {
    "co": "AuditTech Global", "dom": "https://www.audittech-global.com",
    "ind": "Accounting & Audit", "jt": "Tax Planning",
    "jd": "AI-Driven Corporate Tax Strategy",
    "steps": [
        {"sn": "EntityStructureReview", "sv": "EntityReviewService", "c": "Analysis", "dur": 12,
         "d": "AI maps corporate entity structure across jurisdictions, identifies intercompany flows, and evaluates transfer pricing arrangements.",
         "r": "Entity structure determines 60% of tax outcome. Missing a jurisdiction can trigger double taxation.", "sub": [("JurisdictionMapping", 4), ("IntercompanyAnalysis", 4), ("TransferPricingReview", 4)]},
        {"sn": "TaxPositionAnalysis", "sv": "TaxPositionService", "c": "Planning", "dur": 24,
         "d": "AI calculates current vs deferred tax positions, identifies credits, deductions, and incentives. Multi-year tax modelling for strategic decisions.",
         "r": "Proactive tax planning saves 2-5% of revenue for mid-size firms. Missing credits equals leaving money on the table.", "sub": [("CurrentTaxCalc", 8), ("DeferredTaxModelling", 8), ("CreditIdentification", 8)]},
        {"sn": "ComplianceFiling", "sv": "ComplianceService", "c": "Filing", "dur": 48,
         "d": "AI auto-fills tax returns from financial data, validates calculations, and flags exceptions. Multi-jurisdiction filing with deadline management.",
         "r": "Automated filing reduces errors by 70% and meets all deadlines. Late filing penalties range from $5K-500K depending on jurisdiction.", "sub": [("ReturnPreparation", 20), ("ValidationChecks", 16), ("FilingSubmission", 12)]},
        {"sn": "TransferPricingDocumentation", "sv": "TPDocService", "c": "Documentation", "dur": 36,
         "d": "AI generates transfer pricing documentation per OECD guidelines. Benchmarking analysis, functional analysis, and economic analysis automated.",
         "r": "TP documentation is mandatory in 100+ countries. Non-compliance penalties average 10-30% of adjustment amount.", "sub": [("FunctionalAnalysis", 12), ("BenchmarkingStudy", 12), ("ReportGeneration", 12)]},
        {"sn": "AuditDefense", "sv": "AuditDefenseService", "c": "Support", "dur": 72,
         "d": "AI prepares audit defense packages when tax authorities query. Historical data retrieval, precedent analysis, and response drafting.",
         "r": "Well-prepared audit defense resolves 80% of queries without adjustment. Average tax audit assessment is $500K-5M.", "sub": [("QueryAnalysis", 24), ("PrecedentResearch", 24), ("ResponseDrafting", 24)]},
        {"sn": "StrategyOptimization", "sv": "StrategyService", "c": "Advisory", "dur": 24,
         "d": "AI models tax implications of business decisions: M&A, restructuring, new market entry. Scenario analysis for optimal structuring.",
         "r": "Tax-optimised structuring of a $100M acquisition can save $5-15M in taxes. This requires planning before the transaction.", "sub": [("ScenarioModelling", 12), ("StructuringAdvice", 8), ("ImplementationPlan", 4)]}
    ],
    "af": {
        "orderTotal": 120000, "transactionValue": 120000, "averageOrderValue": 95000,
        "contractValue": 350000, "annualRevenue": 12000000, "revenuePerCustomer": 200000,
        "profitMargin": 35.0, "customerLifetimeValue": 2000000, "lifetimeValue": 2000000,
        "acquisitionCost": 20000, "costPerAcquisition": 20000, "conversionProbability": 0.55,
        "conversionRate": 55, "engagementScore": 75, "timeToConversion": 4320,
        "sessionDuration": 3600, "pageViews": 22, "purchaseFrequency": 4,
        "netPromoterScore": 42, "satisfactionRating": 4.1, "retentionProbability": 0.92,
        "processingTime": 10080, "operationalCost": 55000, "efficiencyRating": 78,
        "taxSavings": 1500000, "jurisdictionCount": 12,
        "channel": ["advisory_portal", "secure_document_share", "video_conference", "in_person", "email_encrypted"],
        "deviceType": ["desktop", "desktop", "desktop", "tablet", "mobile"],
        "region": ["Delaware US", "Luxembourg", "Singapore", "Ireland", "Netherlands"],
        "customerSegmentValue": ["multinational", "PE_portfolio", "public_company", "family_office", "startup"],
        "loyaltyTier": ["Platinum", "Gold", "Silver", "Bronze", "New"],
        "segment": ["corporate_tax", "international_tax", "transfer_pricing", "M&A_tax", "indirect_tax"],
        "Productname": ["International Tax Structure Review", "M&A Tax Due Diligence", "Transfer Pricing Study", "R&D Tax Credit Claim", "VAT Recovery Optimisation"],
        "ProductId": ["TAX-INT-001", "TAX-MA-002", "TAX-TP-003", "TAX-RD-004", "TAX-VAT-005"],
        "ProductType": ["advisory", "due_diligence", "compliance", "credit", "recovery"],
        "Price": [350000, 500000, 180000, 95000, 120000],
        "effectiveTaxRate": [18.5, 22.0, 15.0, 25.0, 20.5],
        "taxRiskLevel": ["medium", "high", "low", "low", "medium"],
        "marketTrend": ["pillar_two_compliance", "AI_tax_automation", "real_time_reporting", "ESG_tax_incentives", "crypto_tax"]
    }
},
"config-advertising-campaign-automation.json": {
    "co": "AdTech Dynamics", "dom": "https://www.adtech-dynamics.com",
    "ind": "Advertising & MarTech", "jt": "Campaign Automation",
    "jd": "AI-Driven Advertising Campaign Automation",
    "steps": [
        {"sn": "AudienceSegmentation", "sv": "AudienceService", "c": "Targeting", "dur": 4,
         "d": "AI analyses first-party data, behavioural signals, and lookalike modelling to build high-value audience segments. Privacy-compliant in cookieless environments.",
         "r": "Precise segmentation improves ROAS by 40-60%. Broad targeting wastes 50%+ of ad spend on unqualified impressions.", "sub": [("DataIngestion", 1), ("SegmentBuilding", 2), ("LookalikeModelling", 1)]},
        {"sn": "CreativeOptimization", "sv": "CreativeService", "c": "Production", "dur": 8,
         "d": "AI generates and tests ad creative variants across formats. Dynamic creative optimization adjusts messaging, imagery, and CTAs based on audience segment performance.",
         "r": "Top-performing creative drives 3-5x more conversions than average. DCO improves CTR by 20-35%.", "sub": [("VariantGeneration", 3), ("ABTesting", 3), ("DynamicAssembly", 2)]},
        {"sn": "MediaPlanning", "sv": "MediaPlanningService", "c": "Strategy", "dur": 6,
         "d": "AI allocates budget across channels, platforms, and placements based on predicted performance. Real-time bidding strategy and frequency capping configured.",
         "r": "Optimal media mix improves overall ROAS by 25-40%. Channel allocation errors waste $100K+ on underperforming placements.", "sub": [("ChannelAllocation", 2), ("BudgetDistribution", 2), ("BidStrategyConfig", 2)]},
        {"sn": "CampaignLaunch", "sv": "CampaignLaunchService", "c": "Execution", "dur": 2,
         "d": "Campaigns deployed across Google, Meta, TikTok, programmatic DSPs, and CTV. Tracking pixels, conversion events, and attribution configured.",
         "r": "Clean campaign setup prevents measurement gaps. Missing tracking pixel costs 100% visibility into 15-30% of conversions.", "sub": [("PlatformDeployment", 1), ("TrackingSetup", 0.5), ("QAValidation", 0.5)]},
        {"sn": "PerformanceOptimization", "sv": "OptimizationService", "c": "Monitoring", "dur": 720,
         "d": "AI monitors campaign performance in real-time. Budget reallocation, bid adjustments, audience refinement, and creative rotation automated. Anomaly detection flags spend issues.",
         "r": "Real-time optimization improves ROAS by 15-30% vs weekly manual optimization. Catching a spend anomaly early saves $10K-100K per incident.", "sub": [("RealTimeBidding", 240), ("BudgetPacing", 240), ("AnomalyDetection", 240)]},
        {"sn": "AttributionReporting", "sv": "AttributionService", "c": "Analytics", "dur": 24,
         "d": "Multi-touch attribution model calculates true channel contribution. Incrementality testing validates spend efficiency. Client-facing dashboards auto-generated.",
         "r": "Accurate attribution prevents over-crediting last-click channels by 30-50%. Without it, brands over-invest in brand search and under-invest in upper funnel.", "sub": [("MTA_Modelling", 10), ("IncrementalityTesting", 8), ("DashboardGeneration", 6)]}
    ],
    "af": {
        "orderTotal": 250000, "transactionValue": 250000, "averageOrderValue": 180000,
        "contractValue": 1200000, "annualRevenue": 45000000, "revenuePerCustomer": 600000,
        "profitMargin": 22.0, "customerLifetimeValue": 3600000, "lifetimeValue": 3600000,
        "acquisitionCost": 35000, "costPerAcquisition": 35000, "conversionProbability": 0.38,
        "conversionRate": 38, "engagementScore": 82, "timeToConversion": 1440,
        "sessionDuration": 900, "pageViews": 8, "purchaseFrequency": 12,
        "netPromoterScore": 48, "satisfactionRating": 4.2, "retentionProbability": 0.78,
        "processingTime": 120, "operationalCost": 25000, "efficiencyRating": 85,
        "roas": 4.2, "ctr": 2.8,
        "channel": ["google_ads", "meta_ads", "tiktok_ads", "programmatic_dsp", "ctv"],
        "deviceType": ["mobile", "mobile", "mobile", "desktop", "smart_tv"],
        "region": ["US Northeast", "US West Coast", "UK", "DACH", "Nordics"],
        "customerSegmentValue": ["enterprise_brand", "DTC_brand", "agency_managed", "SMB", "marketplace_seller"],
        "loyaltyTier": ["Platinum", "Gold", "Silver", "Bronze", "Self-Serve"],
        "segment": ["performance", "brand_awareness", "retargeting", "acquisition", "retention"],
        "Productname": ["Google Search Campaign", "Meta Conversion Campaign", "TikTok Brand Lift", "Programmatic Display", "CTV Awareness"],
        "ProductId": ["AD-GS-001", "AD-MF-002", "AD-TT-003", "AD-PG-004", "AD-CT-005"],
        "ProductType": ["search", "social", "video", "display", "CTV"],
        "Price": [300000, 450000, 200000, 150000, 100000],
        "impressions": [5000000, 12000000, 8000000, 20000000, 3000000],
        "clickRate": [3.2, 1.8, 0.9, 0.4, 0],
        "marketTrend": ["cookieless_targeting", "AI_creative_gen", "retail_media_networks", "attention_metrics", "incrementality_measurement"]
    }
},
"config-advertising-programmatic-buying.json": {
    "co": "AdTech Dynamics", "dom": "https://www.adtech-dynamics.com",
    "ind": "Advertising & MarTech", "jt": "Programmatic Buying",
    "jd": "Real-Time Programmatic Media Buying",
    "steps": [
        {"sn": "DealSetup", "sv": "DealSetupService", "c": "Configuration", "dur": 4,
         "d": "Private marketplace deals, preferred deals, and open exchange strategies configured. Supply path optimisation identifies most efficient routes to inventory.",
         "r": "SPO reduces wasted intermediary fees by 15-25%. PMP deals provide 30% better viewability than open exchange.", "sub": [("PMPNegotiation", 2), ("SPOAnalysis", 1), ("DealConfiguration", 1)]},
        {"sn": "BidStrategyConfig", "sv": "BidStrategyService", "c": "Strategy", "dur": 2,
         "d": "AI configures bidding algorithms: target CPA, target ROAS, or max conversions. Floor prices, frequency caps, and brand safety filters applied.",
         "r": "Algorithm-optimised bidding outperforms manual by 20-40%. Wrong bid strategy wastes budget on low-value impressions.", "sub": [("AlgorithmSelection", 1), ("GuardrailSetup", 0.5), ("SafetyFilters", 0.5)]},
        {"sn": "RealTimeBidding", "sv": "RTBService", "c": "Execution", "dur": 720,
         "d": "Bids placed on ad exchanges in <100ms per impression opportunity. AI evaluates user value, context quality, and win probability. Business event: impression_won with bid_price and placement.",
         "r": "100ms decision window requires AI. Winning the right impression at the right price determines 80% of campaign outcome.", "sub": [("ImpressionEvaluation", 240), ("BidCalculation", 240), ("WinRateOptimization", 240)]},
        {"sn": "FraudDetection", "sv": "FraudDetectionService", "c": "Protection", "dur": 720,
         "d": "AI detects invalid traffic, bot clicks, domain spoofing, and ad stacking. Fraudulent impressions blocked pre-bid or refunded post-bid.",
         "r": "Ad fraud costs the industry $80B annually. Without detection, 10-30% of spend goes to fraudulent inventory.", "sub": [("PreBidFiltering", 240), ("PostBidVerification", 240), ("RefundProcessing", 240)]},
        {"sn": "ViewabilityOptimization", "sv": "ViewabilityService", "c": "Quality", "dur": 720,
         "d": "AI tracks viewability, completion rates, and attention metrics. Non-viewable placements excluded. Supply curation improves average viewability from 55% to 80%+.",
         "r": "Ads that aren't viewable have zero impact. Improving viewability from 55% to 80% effectively increases working media by 45%.", "sub": [("ViewabilityTracking", 240), ("PlacementCuration", 240), ("AttentionScoring", 240)]},
        {"sn": "SupplyPathReport", "sv": "ReportingService", "c": "Analytics", "dur": 24,
         "d": "Full transparency reporting on supply path, fees, win rates, and publisher-level performance. Carbon footprint of programmatic activity calculated.",
         "r": "Supply path transparency saves 10-20% by eliminating redundant intermediaries. Carbon reporting increasingly required by brand advertisers.", "sub": [("FeeTransparency", 8), ("PublisherAnalysis", 8), ("CarbonReporting", 8)]}
    ],
    "af": {
        "orderTotal": 500000, "transactionValue": 500000, "averageOrderValue": 350000,
        "contractValue": 2400000, "annualRevenue": 45000000, "revenuePerCustomer": 1200000,
        "profitMargin": 15.0, "customerLifetimeValue": 6000000, "lifetimeValue": 6000000,
        "acquisitionCost": 50000, "costPerAcquisition": 50000, "conversionProbability": 0.42,
        "conversionRate": 42, "engagementScore": 78, "timeToConversion": 720,
        "sessionDuration": 1200, "pageViews": 12, "purchaseFrequency": 12,
        "netPromoterScore": 44, "satisfactionRating": 4.0, "retentionProbability": 0.82,
        "processingTime": 0.1, "operationalCost": 75000, "efficiencyRating": 80,
        "cpm": 8.50, "winRate": 18.5,
        "channel": ["open_exchange", "PMP", "preferred_deal", "programmatic_guaranteed", "CTV_programmatic"],
        "deviceType": ["mobile", "desktop", "tablet", "CTV", "DOOH"],
        "region": ["US", "UK", "Germany", "Japan", "Brazil"],
        "customerSegmentValue": ["agency_holding_co", "indie_agency", "brand_direct", "trading_desk", "performance_buyer"],
        "loyaltyTier": ["Enterprise", "Growth", "Standard", "Starter", "Self-Serve"],
        "segment": ["display", "video", "native", "audio", "DOOH"],
        "Productname": ["Premium Display Package", "Video Pre-Roll Suite", "Native Content Hub", "Audio Streaming Ads", "DOOH Network Buy"],
        "ProductId": ["PG-DP-001", "PG-VD-002", "PG-NT-003", "PG-AU-004", "PG-DO-005"],
        "ProductType": ["display", "video", "native", "audio", "out_of_home"],
        "Price": [500000, 800000, 300000, 200000, 600000],
        "impressionsServed": [62000000, 15000000, 8000000, 25000000, 4000000],
        "fraudRate": [2.1, 3.8, 1.5, 0.8, 0.2],
        "marketTrend": ["SPO_optimization", "attention_economy", "carbon_neutral_media", "AI_bidding", "retail_media"]
    }
},
"config-beauty-product-lifecycle.json": {
    "co": "BeautyTech Labs", "dom": "https://www.beautytech-labs.com",
    "ind": "Beauty & Cosmetics", "jt": "Product Lifecycle",
    "jd": "AI-Driven Beauty Product Lifecycle Management",
    "steps": [
        {"sn": "TrendDiscovery", "sv": "TrendDiscoveryService", "c": "Research", "dur": 72,
         "d": "AI scans social media, influencer content, runway trends, and ingredient patents to identify emerging beauty trends. Consumer sentiment analysis predicts demand 6-12 months ahead.",
         "r": "Trend-aligned products generate 3-5x higher launch velocity. Missing a trend by 6 months means entering a saturated market.", "sub": [("SocialListening", 24), ("InfluencerAnalysis", 24), ("IngredientTrending", 24)]},
        {"sn": "FormulationDesign", "sv": "FormulationService", "c": "Development", "dur": 480,
         "d": "AI assists formulation chemists with ingredient compatibility, efficacy prediction, and stability modelling. Regulatory compliance checked across target markets.",
         "r": "AI-assisted formulation reduces development cycles from 18 months to 8 months. Stability prediction prevents costly reformulation after launch.", "sub": [("IngredientOptimization", 160), ("StabilityModelling", 160), ("RegulatoryCheck", 160)]},
        {"sn": "ConsumerTesting", "sv": "TestingService", "c": "Validation", "dur": 720,
         "d": "Virtual try-on testing, panel blind testing, and dermatological assessment. AI predicts NPS from early test results. Claims substantiation for marketing.",
         "r": "Consumer testing validation improves launch success rate from 25% to 60%. Claims without substantiation risk regulatory action.", "sub": [("VirtualTryOn", 240), ("PanelTesting", 240), ("ClaimsSubstantiation", 240)]},
        {"sn": "PackagingDesign", "sv": "PackagingService", "c": "Design", "dur": 240,
         "d": "AI generates packaging designs aligned with brand guidelines and sustainability targets. Shelf impact simulation and cost-per-unit optimization.",
         "r": "Packaging drives 64% of first-time purchase decisions. Sustainable packaging commands 15-25% price premium in beauty.", "sub": [("DesignGeneration", 80), ("SustainabilityReview", 80), ("ShelfSimulation", 80)]},
        {"sn": "LaunchPlanning", "sv": "LaunchPlanningService", "c": "Go-to-Market", "dur": 168,
         "d": "AI optimises launch timing, channel allocation, influencer seeding, and pricing strategy. Demand forecasting drives initial production run size.",
         "r": "Optimised launch timing improves first-month sales by 30-50%. Overproduction wastes materials; underproduction misses the hype window.", "sub": [("TimingOptimization", 56), ("InfluencerSeeding", 56), ("DemandForecasting", 56)]},
        {"sn": "PostLaunchOptimization", "sv": "PostLaunchService", "c": "Optimization", "dur": 2160,
         "d": "AI monitors reviews, returns, repurchase rates, and social sentiment. Product improvements recommended. SKU rationalisation when products underperform.",
         "r": "Post-launch optimisation extends product lifecycle by 40%. Early review monitoring enables rapid reformulation before negative perception sets in.", "sub": [("ReviewMonitoring", 720), ("RepurchaseAnalysis", 720), ("SKUOptimization", 720)]}
    ],
    "af": {
        "orderTotal": 42, "transactionValue": 42, "averageOrderValue": 55,
        "contractValue": 0, "annualRevenue": 180000000, "revenuePerCustomer": 280,
        "profitMargin": 68.0, "customerLifetimeValue": 2400, "lifetimeValue": 2400,
        "acquisitionCost": 18, "costPerAcquisition": 18, "conversionProbability": 0.12,
        "conversionRate": 12, "engagementScore": 88, "timeToConversion": 360,
        "sessionDuration": 480, "pageViews": 15, "purchaseFrequency": 6,
        "netPromoterScore": 58, "satisfactionRating": 4.4, "retentionProbability": 0.65,
        "processingTime": 120, "operationalCost": 8, "efficiencyRating": 82,
        "shelfLife": 24, "ingredientCount": 28,
        "channel": ["DTC_website", "sephora", "ulta", "amazon", "tiktok_shop"],
        "deviceType": ["mobile", "mobile", "desktop", "mobile", "mobile"],
        "region": ["US", "China", "EU", "Japan", "Middle East"],
        "customerSegmentValue": ["gen_z", "millennial", "prestige_buyer", "clean_beauty", "K_beauty_fan"],
        "loyaltyTier": ["VIP", "Gold", "Silver", "Basic", "New"],
        "segment": ["skincare", "makeup", "haircare", "fragrance", "bodycare"],
        "Productname": ["Retinol Night Serum", "Hyaluronic Acid Moisturiser", "Vitamin C Brightening Cream", "Niacinamide Pore Minimiser", "SPF50 Mineral Sunscreen"],
        "ProductId": ["BTY-SK-001", "BTY-SK-002", "BTY-SK-003", "BTY-SK-004", "BTY-SN-005"],
        "ProductType": ["serum", "moisturiser", "cream", "treatment", "sunscreen"],
        "Price": [48, 36, 42, 28, 32],
        "reviewRating": [4.6, 4.4, 4.5, 4.3, 4.7],
        "repurchaseRate": [0.45, 0.52, 0.38, 0.42, 0.55],
        "marketTrend": ["clean_beauty", "skinimalism", "AI_skin_analysis", "microbiome_skincare", "refillable_packaging"]
    }
},
"config-beauty-virtual-tryon.json": {
    "co": "BeautyTech Labs", "dom": "https://www.beautytech-labs.com",
    "ind": "Beauty & Cosmetics", "jt": "Virtual Try-On",
    "jd": "AI-Powered Virtual Beauty Try-On Experience",
    "steps": [
        {"sn": "FaceMapping", "sv": "FaceMappingService", "c": "Detection", "dur": 0.5,
         "d": "AI maps facial landmarks, skin tone, undertone, and features in real-time using device camera. Privacy-preserving on-device processing. Business event: face_detected with skin_type and features.",
         "r": "Accurate face mapping drives 85% try-on satisfaction. Poor detection causes misaligned product rendering and immediate drop-off.", "sub": [("LandmarkDetection", 0.2), ("SkinToneAnalysis", 0.2), ("FeatureClassification", 0.1)]},
        {"sn": "ProductRecommendation", "sv": "RecommendationService", "c": "Personalization", "dur": 1,
         "d": "AI recommends products based on skin analysis, stated preferences, purchase history, and trending products. Shade matching with 95% accuracy across all skin tones.",
         "r": "Personalised recommendations drive 40% higher add-to-cart rates. Inclusive shade matching is a brand reputation imperative.", "sub": [("ShadeMatching", 0.3), ("SkinConcernMatch", 0.3), ("TrendIntegration", 0.4)]},
        {"sn": "VirtualApplication", "sv": "RenderingService", "c": "Experience", "dur": 0.1,
         "d": "Real-time rendering of lipstick, eyeshadow, foundation, and other products on live camera feed. Multiple product layering supported. Before/after comparison.",
         "r": "Realistic rendering is the core value. Users who try-on products are 2.5x more likely to purchase than those who don't.", "sub": [("ProductRendering", 0.05), ("LayerCompositing", 0.03), ("LightingAdjustment", 0.02)]},
        {"sn": "SkinAnalysis", "sv": "SkinAnalysisService", "c": "Assessment", "dur": 2,
         "d": "AI performs deep skin health assessment: pores, wrinkles, dark spots, redness, hydration. Generates personalised skincare routine recommendation.",
         "r": "Skin analysis drives 65% higher skincare basket value. Customers trust AI analysis more than self-assessment for product selection.", "sub": [("ConcernDetection", 0.8), ("RoutineGeneration", 0.8), ("ProgressTracking", 0.4)]},
        {"sn": "SocialSharing", "sv": "SharingService", "c": "Engagement", "dur": 0.5,
         "d": "Users save and share try-on looks on social media. Branded filters and AR effects drive viral sharing. Business event: look_shared with products and platform.",
         "r": "Social sharing drives 25% of new app downloads. Each shared look generates an average of 12 impressions.", "sub": [("LookCapture", 0.2), ("FilterApplication", 0.1), ("PlatformSharing", 0.2)]},
        {"sn": "ConversionTracking", "sv": "ConversionService", "c": "Analytics", "dur": 0.1,
         "d": "End-to-end tracking from try-on to purchase. AI attributes revenue to specific product try-ons, shade matches, and skin analysis recommendations.",
         "r": "Try-on attribution justifies continued investment. Proving 2.5x conversion lift secures ongoing feature development budget.", "sub": [("TryOnAttribution", 0.05), ("RevenueMapping", 0.03), ("LiftAnalysis", 0.02)]}
    ],
    "af": {
        "orderTotal": 65, "transactionValue": 65, "averageOrderValue": 55,
        "contractValue": 0, "annualRevenue": 180000000, "revenuePerCustomer": 280,
        "profitMargin": 68.0, "customerLifetimeValue": 2400, "lifetimeValue": 2400,
        "acquisitionCost": 12, "costPerAcquisition": 12, "conversionProbability": 0.22,
        "conversionRate": 22, "engagementScore": 92, "timeToConversion": 15,
        "sessionDuration": 600, "pageViews": 8, "purchaseFrequency": 6,
        "netPromoterScore": 62, "satisfactionRating": 4.5, "retentionProbability": 0.72,
        "processingTime": 0.1, "operationalCost": 0.01, "efficiencyRating": 95,
        "tryOnCount": 8, "shadeAccuracy": 95.2,
        "channel": ["mobile_app", "website_AR", "instagram_filter", "snapchat_lens", "in_store_mirror"],
        "deviceType": ["mobile", "mobile", "mobile", "mobile", "kiosk"],
        "region": ["US", "China", "Japan", "South Korea", "France"],
        "customerSegmentValue": ["beauty_enthusiast", "casual_shopper", "influencer", "gifter", "first_time_buyer"],
        "loyaltyTier": ["Beauty Insider", "VIB", "Rouge", "Basic", "New"],
        "segment": ["lipstick", "foundation", "eyeshadow", "blush", "skincare"],
        "Productname": ["Velvet Matte Lip", "Skin Tint Foundation", "Smoky Eye Palette", "Cream Blush Duo", "Glass Skin Serum"],
        "ProductId": ["BTY-LP-001", "BTY-FD-002", "BTY-ES-003", "BTY-BL-004", "BTY-SR-005"],
        "ProductType": ["lip_colour", "foundation", "eye_palette", "blush", "serum"],
        "Price": [32, 45, 55, 28, 62],
        "tryOnConversionRate": [0.28, 0.22, 0.18, 0.24, 0.15],
        "shadeRange": [40, 55, 24, 12, 1],
        "marketTrend": ["AR_try_on", "AI_shade_match", "skin_diagnostics", "virtual_consultation", "social_commerce"]
    }
},
"config-chemical-process-optimization.json": {
    "co": "ChemTech Industries", "dom": "https://www.chemtech-industries.com",
    "ind": "Chemical & Process Industries", "jt": "Process Optimization",
    "jd": "AI-Driven Chemical Process Optimization",
    "steps": [
        {"sn": "ProcessModelling", "sv": "ProcessModelService", "c": "Analysis", "dur": 48,
         "d": "AI builds digital twin of chemical process from sensor data, batch records, and thermodynamic models. Identifies yield-limiting steps and energy waste points.",
         "r": "Digital twin modelling identifies 5-15% yield improvement opportunities. Each 1% yield improvement in a $100M plant = $1M annual savings.", "sub": [("SensorDataIngestion", 16), ("ThermodynamicModelling", 16), ("YieldAnalysis", 16)]},
        {"sn": "RecipeOptimization", "sv": "RecipeOptimizationService", "c": "Optimization", "dur": 72,
         "d": "AI optimises batch recipe parameters: temperature profiles, reaction times, catalyst ratios, and addition sequences. Multi-objective optimization balances yield, quality, and energy.",
         "r": "Recipe optimization improves batch yield by 3-8% and reduces cycle time by 10-20%. Even small improvements compound across thousands of batches.", "sub": [("ParameterSweep", 24), ("QualityConstraints", 24), ("EnergyMinimization", 24)]},
        {"sn": "QualityPrediction", "sv": "QualityPredictionService", "c": "Control", "dur": 0.5,
         "d": "Real-time quality prediction from in-process measurements. AI predicts final batch quality during production, enabling mid-batch corrections before off-spec material is produced.",
         "r": "Mid-batch correction reduces off-spec production by 40-60%. Each off-spec batch costs $50K-500K in rework or disposal.", "sub": [("InProcessMeasurement", 0.2), ("QualityModelling", 0.2), ("CorrectionRecommendation", 0.1)]},
        {"sn": "EnergyManagement", "sv": "EnergyManagementService", "c": "Efficiency", "dur": 24,
         "d": "AI optimises energy consumption across steam, cooling, compressed air, and electrical systems. Load shifting to off-peak periods and heat recovery optimization.",
         "r": "Energy is 20-40% of chemical production cost. AI optimization typically saves 8-15% of energy spend without capital investment.", "sub": [("LoadAnalysis", 8), ("HeatRecovery", 8), ("PeakShifting", 8)]},
        {"sn": "MaintenancePrediction", "sv": "MaintenancePredictionService", "c": "Reliability", "dur": 168,
         "d": "AI predicts equipment failures from vibration, temperature, pressure, and corrosion sensor data. Maintenance windows optimised around production schedule.",
         "r": "Unplanned shutdown of a chemical reactor costs $100K-1M per day. Predictive maintenance reduces unplanned downtime by 35-50%.", "sub": [("VibrationAnalysis", 56), ("CorrosionMonitoring", 56), ("ScheduleOptimization", 56)]},
        {"sn": "RegulatoryCompliance", "sv": "ComplianceService", "c": "Compliance", "dur": 24,
         "d": "AI monitors emissions, effluent, and waste against permit limits in real-time. Automatic adjustments to stay within limits. Regulatory reporting auto-generated.",
         "r": "EPA/REACH violations can result in $50K-1M daily fines and plant shutdown orders. Proactive monitoring prevents exceedances before they occur.", "sub": [("EmissionsMonitoring", 8), ("EffluentTracking", 8), ("ReportGeneration", 8)]}
    ],
    "af": {
        "orderTotal": 2500000, "transactionValue": 2500000, "averageOrderValue": 1800000,
        "contractValue": 15000000, "annualRevenue": 500000000, "revenuePerCustomer": 8000000,
        "profitMargin": 12.0, "customerLifetimeValue": 40000000, "lifetimeValue": 40000000,
        "acquisitionCost": 200000, "costPerAcquisition": 200000, "conversionProbability": 0.75,
        "conversionRate": 75, "engagementScore": 70, "timeToConversion": 4320,
        "sessionDuration": 3600, "pageViews": 10, "purchaseFrequency": 4,
        "netPromoterScore": 40, "satisfactionRating": 3.8, "retentionProbability": 0.92,
        "processingTime": 720, "operationalCost": 350000, "efficiencyRating": 78,
        "batchYield": 94.5, "energyPerTonne": 1850,
        "channel": ["plant_SCADA", "engineering_portal", "mobile_rounds", "lab_LIMS", "ERP_integration"],
        "deviceType": ["HMI_panel", "desktop", "ruggedised_tablet", "desktop", "server"],
        "region": ["Houston TX", "Rotterdam NL", "Shanghai CN", "Mumbai IN", "Ludwigshafen DE"],
        "customerSegmentValue": ["petrochem", "specialty_chem", "pharma_API", "agrochem", "polymer"],
        "loyaltyTier": ["Strategic", "Key", "Developing", "Transactional", "Spot"],
        "segment": ["bulk_chemical", "specialty_chemical", "pharmaceutical_intermediate", "agrochemical", "polymer"],
        "Productname": ["Ethylene Oxide", "TDI Isocyanate", "Ibuprofen API", "Glyphosate Concentrate", "HDPE Resin"],
        "ProductId": ["CHM-EO-001", "CHM-TD-002", "CHM-IB-003", "CHM-GL-004", "CHM-PE-005"],
        "ProductType": ["commodity", "specialty", "API", "agrochemical", "polymer"],
        "Price": [1200, 3500, 45000, 2800, 1650],
        "purityGrade": [99.9, 99.5, 99.95, 98.0, 99.0],
        "hazardClass": ["flammable", "toxic", "OEB3", "toxic", "non_hazardous"],
        "marketTrend": ["green_chemistry", "process_intensification", "circular_economy", "bio_based_feedstock", "continuous_manufacturing"]
    }
},
"config-chemical-safety-compliance.json": {
    "co": "ChemTech Industries", "dom": "https://www.chemtech-industries.com",
    "ind": "Chemical & Process Industries", "jt": "Safety Compliance",
    "jd": "AI-Enhanced Chemical Safety & EHS Management",
    "steps": [
        {"sn": "HazardIdentification", "sv": "HazardService", "c": "Assessment", "dur": 24,
         "d": "AI performs PHA/HAZOP analysis using process flow diagrams and material safety data. Identifies hazard scenarios, assigns risk rankings, and recommends safeguards.",
         "r": "Comprehensive HAZOP prevents catastrophic incidents. Chemical plant major accidents cost $50M-$1B and cause fatalities.", "sub": [("ScenarioGeneration", 8), ("RiskRanking", 8), ("SafeguardMapping", 8)]},
        {"sn": "RealTimeSafetyMonitoring", "sv": "SafetyMonitorService", "c": "Monitoring", "dur": 8760,
         "d": "AI monitors gas detectors, pressure relief, temperature alarms, and SIL-rated safety systems 24/7. Predictive analysis of safety system degradation.",
         "r": "Real-time monitoring prevents 90% of preventable incidents. Safety system failures that go undetected are the primary cause of major accidents.", "sub": [("GasDetection", 2920), ("PressureMonitoring", 2920), ("SILVerification", 2920)]},
        {"sn": "IncidentManagement", "sv": "IncidentService", "c": "Response", "dur": 4,
         "d": "AI-assisted emergency response: automatic isolation, ventilation control, and emergency services notification. Plume modelling for gas release scenarios. Evacuation route optimisation.",
         "r": "Automated emergency response reduces reaction time from 10 minutes to 30 seconds. In chemical emergencies, every second matters.", "sub": [("AutoIsolation", 1), ("PlumeModelling", 1.5), ("EvacuationRouting", 1.5)]},
        {"sn": "RegulatoryReporting", "sv": "RegulatoryService", "c": "Compliance", "dur": 48,
         "d": "AI auto-generates OSHA PSM, EPA RMP, COMAH, and Seveso reports. Tracks regulatory changes across jurisdictions and flags compliance gaps.",
         "r": "PSM/RMP non-compliance can shut a plant down. Average OSHA fine for serious PSM violation is $150K. Plant shutdowns cost $1M+/day.", "sub": [("PSMCompliance", 16), ("RPMReporting", 16), ("ChangeTracking", 16)]},
        {"sn": "TrainingAndCompetency", "sv": "TrainingService", "c": "Development", "dur": 168,
         "d": "AI tracks operator training requirements, competency assessments, and refresher schedules. VR-based emergency response training. Business event: competency_verified with operator_id and skill_level.",
         "r": "80% of chemical incidents involve human error. Competency-based training reduces human error incidents by 45%.", "sub": [("CompetencyTracking", 48), ("VRTraining", 72), ("RefresherScheduling", 48)]},
        {"sn": "ContinuousImprovement", "sv": "ImprovementService", "c": "Analytics", "dur": 720,
         "d": "AI analyses near-misses, incidents, and audit findings to identify systemic patterns. Leading safety indicators tracked and benchmarked against industry standards.",
         "r": "For every major accident there are 30 near-misses. Organisations that analyse near-misses reduce major accident frequency by 60%.", "sub": [("NearMissAnalysis", 240), ("LeadingIndicators", 240), ("BenchmarkReporting", 240)]}
    ],
    "af": {
        "orderTotal": 0, "transactionValue": 0, "averageOrderValue": 0,
        "contractValue": 2000000, "annualRevenue": 500000000, "revenuePerCustomer": 0,
        "profitMargin": 12.0, "customerLifetimeValue": 0, "lifetimeValue": 0,
        "acquisitionCost": 0, "costPerAcquisition": 0, "conversionProbability": 1.0,
        "conversionRate": 100, "engagementScore": 95, "timeToConversion": 0,
        "sessionDuration": 480, "pageViews": 5, "purchaseFrequency": 365,
        "netPromoterScore": 0, "satisfactionRating": 0, "retentionProbability": 1.0,
        "processingTime": 60, "operationalCost": 500000, "efficiencyRating": 88,
        "incidentRate": 0.3, "nearMissRate": 4.5,
        "channel": ["SCADA_alarm", "field_tablet", "control_room", "safety_kiosk", "mobile_alert"],
        "deviceType": ["HMI_panel", "ruggedised_tablet", "desktop", "kiosk", "mobile"],
        "region": ["Texas US", "Rotterdam NL", "Jurong SG", "Antwerp BE", "Jamnagar IN"],
        "customerSegmentValue": ["petrochemical", "fine_chemical", "pharmaceutical", "food_processing", "water_treatment"],
        "loyaltyTier": ["Tier 1 Site", "Tier 2 Site", "Satellite", "Contract", "JV"],
        "segment": ["process_safety", "occupational_health", "environmental", "transport_safety", "security"],
        "Productname": ["PSM Compliance Suite", "Gas Detection Network", "SIL Lifecycle Manager", "Emergency Response System", "EHS Training Platform"],
        "ProductId": ["SAF-PS-001", "SAF-GD-002", "SAF-SL-003", "SAF-ER-004", "SAF-TR-005"],
        "ProductType": ["compliance", "detection", "safety_system", "emergency", "training"],
        "Price": [500000, 350000, 800000, 200000, 150000],
        "complianceScore": [96, 94, 98, 92, 90],
        "hazardCategory": ["highly_flammable", "toxic", "explosive", "corrosive", "oxidising"],
        "marketTrend": ["AI_safety_analytics", "digital_SIL_management", "VR_emergency_training", "predictive_safety", "process_safety_4.0"]
    }
},
}

if __name__ == "__main__":
    for fn, data in SECTORS.items():
        gen(fn, data)
    print(f"Batch 2 complete: {len(SECTORS)} configs updated.")
