#!/usr/bin/env python3
"""Batch 3: consulting, cybersecurity, datacentre, delivery"""
import json, os, uuid

CONFIGS_DIR = os.path.join(os.path.dirname(__file__), '..', 'saved-configs')

def gen(fn, d):
    steps = []
    for i, s in enumerate(d["steps"], 1):
        st = {"stepIndex": i, "stepName": s["sn"], "serviceName": s["sv"], "description": s["d"],
              "category": s["c"], "estimatedDuration": s["dur"], "businessRationale": s["r"],
              "substeps": [{"substepName": n, "duration": dur} for n, dur in s["sub"]]}
        if i == 1: st["timestamp"] = "2025-11-21T00:00:00.000Z"
        steps.append(st)
    config = {"companyName": d["co"], "domain": d["dom"], "industryType": d["ind"],
              "journeyType": d["jt"], "journeyDetail": d["jd"],
              "journeyId": f"journey_{d['jt'].lower().replace(' ','_')}_{uuid.uuid4().hex[:8]}",
              "journeyStartTime": "2025-11-21T00:00:00.000Z", "steps": steps,
              "id": str(uuid.uuid4()), "name": f"{d['ind']} - {d['jt']}",
              "timestamp": "2026-03-18T12:00:00.000Z", "source": "sector-demo",
              "additionalFields": d["af"]}
    with open(os.path.join(CONFIGS_DIR, fn), 'w') as f: json.dump(config, f, indent=4)
    print(f"  ✅ {fn}")

SECTORS = {
"config-consulting-engagement-delivery.json": {
    "co": "ConsultCo Partners", "dom": "https://www.consultco-partners.com",
    "ind": "Consulting & Professional Services", "jt": "Engagement Delivery",
    "jd": "AI-Enhanced Consulting Engagement Lifecycle",
    "steps": [
        {"sn": "ScopeDefinition", "sv": "ScopeService", "c": "Initiation", "dur": 16,
         "d": "AI analyses client requirements, prior engagements, and industry benchmarks to define scope, deliverables, and resource requirements. SOW auto-drafted.",
         "r": "Scope creep causes 40% of project overruns. Clear AI-scoped SOWs reduce change requests by 35%.", "sub": [("RequirementsAnalysis", 6), ("BenchmarkComparison", 4), ("SOWDrafting", 6)]},
        {"sn": "TeamStaffing", "sv": "StaffingService", "c": "Resourcing", "dur": 8,
         "d": "AI matches consultants to engagement based on skills, industry expertise, client history, and availability. Utilisation targets balanced across the practice.",
         "r": "Right-staffing improves client satisfaction by 30% and consultant utilisation by 8%. Mismatched skills cause rework and margin erosion.", "sub": [("SkillMatching", 3), ("AvailabilityCheck", 2), ("UtilisationBalancing", 3)]},
        {"sn": "ResearchAndAnalysis", "sv": "ResearchService", "c": "Discovery", "dur": 80,
         "d": "AI assists with data collection, market analysis, competitor benchmarking, and best practice research. Automated survey analysis and interview summarisation.",
         "r": "AI-assisted research accelerates discovery by 50%. Consultants spend time on insights rather than data gathering.", "sub": [("DataCollection", 30), ("MarketAnalysis", 25), ("BenchmarkResearch", 25)]},
        {"sn": "InsightDevelopment", "sv": "InsightService", "c": "Analysis", "dur": 40,
         "d": "AI identifies patterns, correlations, and opportunities from research data. Hypothesis testing and scenario modelling. Draft recommendations generated.",
         "r": "AI-augmented insights are 40% more data-driven. Stronger evidence base improves client buy-in and implementation rates.", "sub": [("PatternRecognition", 15), ("ScenarioModelling", 15), ("RecommendationDrafting", 10)]},
        {"sn": "ClientPresentation", "sv": "PresentationService", "c": "Delivery", "dur": 16,
         "d": "AI generates presentation decks from insights, visualises data, and prepares executive summaries. Rehearsal feedback and Q&A preparation.",
         "r": "Compelling presentations drive implementation decisions. 60% of consulting value is lost if recommendations aren't acted upon.", "sub": [("DeckGeneration", 6), ("DataVisualisation", 4), ("ExecSummary", 6)]},
        {"sn": "ImplementationSupport", "sv": "ImplementationService", "c": "Follow-through", "dur": 480,
         "d": "AI tracks recommendation implementation progress, measures outcome metrics, and provides ongoing advisory. Value realisation tracked against business case.",
         "r": "Implementation support converts 60% of recommendations vs 20% without. This drives repeat engagement revenue.", "sub": [("ProgressTracking", 160), ("OutcomeMeasurement", 160), ("AdvisorySupport", 160)]}
    ],
    "af": {
        "orderTotal": 250000, "transactionValue": 250000, "averageOrderValue": 180000,
        "contractValue": 750000, "annualRevenue": 25000000, "revenuePerCustomer": 500000,
        "profitMargin": 32.0, "customerLifetimeValue": 4000000, "lifetimeValue": 4000000,
        "acquisitionCost": 50000, "costPerAcquisition": 50000, "conversionProbability": 0.35,
        "conversionRate": 35, "engagementScore": 78, "timeToConversion": 4320,
        "sessionDuration": 3600, "pageViews": 20, "purchaseFrequency": 3,
        "netPromoterScore": 52, "satisfactionRating": 4.2, "retentionProbability": 0.82,
        "processingTime": 2880, "operationalCost": 120000, "efficiencyRating": 76,
        "utilisationRate": 72, "realisationRate": 88,
        "channel": ["partner_referral", "RFP_response", "website_inquiry", "conference_lead", "existing_client"],
        "deviceType": ["desktop", "desktop", "mobile", "tablet", "desktop"],
        "region": ["New York", "London", "Singapore", "Dubai", "Sydney"],
        "customerSegmentValue": ["fortune_500", "mid_market", "PE_portfolio", "government", "startup_scale"],
        "loyaltyTier": ["Strategic", "Key", "Growth", "Transactional", "New"],
        "segment": ["strategy", "operations", "digital", "M&A", "people_and_org"],
        "Productname": ["Digital Transformation Strategy", "Operating Model Redesign", "M&A Due Diligence", "Cost Optimisation Programme", "Customer Experience Overhaul"],
        "ProductId": ["CON-DT-001", "CON-OM-002", "CON-MA-003", "CON-CO-004", "CON-CX-005"],
        "ProductType": ["strategy", "operations", "transaction", "cost", "experience"],
        "Price": [500000, 350000, 750000, 250000, 400000],
        "consultantDays": [120, 85, 200, 60, 95],
        "clientSatisfaction": [4.5, 4.2, 4.0, 4.3, 4.6],
        "marketTrend": ["AI_augmented_consulting", "outcome_based_fees", "platform_consulting", "ESG_advisory", "fractional_CxO"]
    }
},
"config-consulting-resource-planning.json": {
    "co": "ConsultCo Partners", "dom": "https://www.consultco-partners.com",
    "ind": "Consulting & Professional Services", "jt": "Resource Planning",
    "jd": "AI-Driven Consulting Resource Optimization",
    "steps": [
        {"sn": "DemandForecasting", "sv": "DemandForecastService", "c": "Planning", "dur": 24,
         "d": "AI forecasts resource demand from pipeline, proposals, and historical patterns. Skill gap analysis identifies hiring needs 3-6 months ahead.",
         "r": "Accurate demand forecasting prevents bench costs ($15K/month per idle consultant) and missed revenue from understaffing.", "sub": [("PipelineAnalysis", 8), ("PatternForecasting", 8), ("GapIdentification", 8)]},
        {"sn": "CapacityPlanning", "sv": "CapacityService", "c": "Allocation", "dur": 8,
         "d": "AI optimises consultant allocation across active and upcoming engagements. Balances utilisation targets with skill development, travel preferences, and client relationships.",
         "r": "Optimal capacity planning improves utilisation from 65% to 78%. Each 1% utilisation improvement = $250K revenue for a 100-person practice.", "sub": [("AllocationOptimization", 3), ("PreferenceMatching", 2), ("UtilisationBalancing", 3)]},
        {"sn": "SkillDevelopment", "sv": "SkillDevService", "c": "Development", "dur": 40,
         "d": "AI identifies skill gaps vs market demand and recommends learning paths. Training investments prioritised by ROI and engagement win potential.",
         "r": "Targeted upskilling generates 5x ROI vs generic training. Emerging skill capabilities open new revenue streams.", "sub": [("GapAnalysis", 12), ("LearningPathDesign", 16), ("ROICalculation", 12)]},
        {"sn": "ContractorManagement", "sv": "ContractorService", "c": "Procurement", "dur": 16,
         "d": "AI manages contractor pool for demand spikes. Rate negotiation, compliance verification, and performance tracking. Builds preferred contractor database.",
         "r": "Smart contractor management reduces supplemental staffing costs by 20-30% while maintaining quality standards.", "sub": [("PoolManagement", 6), ("RateOptimization", 4), ("PerformanceTracking", 6)]},
        {"sn": "PerformanceAnalytics", "sv": "PerformanceService", "c": "Analytics", "dur": 24,
         "d": "AI tracks consultant performance across engagements: client feedback, delivery quality, skill growth, and revenue generation. Promotion readiness assessment.",
         "r": "Data-driven performance management reduces voluntary attrition by 15%. Top talent retention is the #1 challenge in consulting.", "sub": [("FeedbackAggregation", 8), ("GrowthTracking", 8), ("PromotionAssessment", 8)]},
        {"sn": "WorkforceForecasting", "sv": "WorkforceService", "c": "Strategy", "dur": 168,
         "d": "AI models workforce supply/demand scenarios under different growth assumptions. Hiring plans, office capacity, and expansion decisions informed by predictive models.",
         "r": "Workforce planning drives the P&L. Hiring too fast creates bench; hiring too slow misses revenue by $500K+ per unfilled senior role.", "sub": [("ScenarioModelling", 56), ("HiringPlans", 56), ("ExpansionAnalysis", 56)]}
    ],
    "af": {
        "orderTotal": 180000, "transactionValue": 180000, "averageOrderValue": 150000,
        "contractValue": 500000, "annualRevenue": 25000000, "revenuePerCustomer": 400000,
        "profitMargin": 30.0, "customerLifetimeValue": 3200000, "lifetimeValue": 3200000,
        "acquisitionCost": 40000, "costPerAcquisition": 40000, "conversionProbability": 0.40,
        "conversionRate": 40, "engagementScore": 75, "timeToConversion": 2160,
        "sessionDuration": 2400, "pageViews": 15, "purchaseFrequency": 4,
        "netPromoterScore": 48, "satisfactionRating": 4.0, "retentionProbability": 0.85,
        "processingTime": 1440, "operationalCost": 85000, "efficiencyRating": 74,
        "utilisationTarget": 75, "voluntaryAttrition": 12.5,
        "channel": ["resource_portal", "staffing_app", "email", "manager_request", "self_service"],
        "deviceType": ["desktop", "mobile", "desktop", "desktop", "mobile"],
        "region": ["New York", "London", "Singapore", "Chicago", "Mumbai"],
        "customerSegmentValue": ["partner", "director", "manager", "senior_consultant", "analyst"],
        "loyaltyTier": ["Partner", "Director", "Manager", "Senior", "Junior"],
        "segment": ["strategy", "digital", "operations", "technology", "people"],
        "Productname": ["Due Diligence Sprint", "Digital Assessment", "Operations Review", "IT Strategy", "Org Design"],
        "ProductId": ["RES-DD-001", "RES-DA-002", "RES-OR-003", "RES-IT-004", "RES-OD-005"],
        "ProductType": ["transaction", "assessment", "review", "strategy", "design"],
        "Price": [200000, 150000, 120000, 180000, 100000],
        "teamSize": [4, 3, 5, 3, 4],
        "engagementDuration": [6, 8, 12, 10, 8],
        "marketTrend": ["AI_staffing", "skills_marketplace", "gig_consulting", "remote_delivery", "outcome_pricing"]
    }
},
"config-cybersecurity-incident-response.json": {
    "co": "CyberShield Security", "dom": "https://www.cybershield-security.com",
    "ind": "Cybersecurity", "jt": "Incident Response",
    "jd": "AI-Automated Cybersecurity Incident Response",
    "steps": [
        {"sn": "ThreatDetection", "sv": "ThreatDetectionService", "c": "Detection", "dur": 0.05,
         "d": "AI SIEM correlates log data from endpoints, network, cloud, and identity systems. ML models detect anomalous behavior, known attack signatures, and zero-day indicators.",
         "r": "Mean time to detect (MTTD) is the #1 driver of breach cost. Reducing MTTD from 200 days to hours saves an average of $1.2M per breach.", "sub": [("LogCorrelation", 0.02), ("AnomalyDetection", 0.02), ("AlertGeneration", 0.01)]},
        {"sn": "AlertTriage", "sv": "TriageService", "c": "Analysis", "dur": 0.5,
         "d": "AI enriches alerts with threat intelligence, asset criticality, and user context. Auto-classifies severity and assigns to appropriate response team. 95% of false positives filtered.",
         "r": "SOC analysts face 10,000+ alerts/day. AI triage reduces analyst fatigue and ensures critical alerts aren't buried in noise.", "sub": [("ThreatEnrichment", 0.2), ("SeverityClassification", 0.15), ("TeamRouting", 0.15)]},
        {"sn": "ContainmentAction", "sv": "ContainmentService", "c": "Response", "dur": 0.25,
         "d": "Automated containment: isolate compromised endpoints, block malicious IPs, disable compromised accounts, and quarantine suspicious files. Human approval for high-impact actions.",
         "r": "Automated containment reduces mean time to respond (MTTR) from 72 hours to minutes. Each hour of uncontained breach costs $10K-100K.", "sub": [("EndpointIsolation", 0.08), ("NetworkBlocking", 0.08), ("AccountLockdown", 0.09)]},
        {"sn": "ForensicInvestigation", "sv": "ForensicsService", "c": "Investigation", "dur": 48,
         "d": "AI-assisted forensic analysis: timeline reconstruction, lateral movement mapping, data exfiltration assessment, and attribution. Evidence preserved chain-of-custody compliant.",
         "r": "Thorough forensics determines breach scope, which drives notification requirements. Missing compromised systems means the attacker returns.", "sub": [("TimelineReconstruction", 16), ("LateralMovementMapping", 16), ("ExfiltrationAssessment", 16)]},
        {"sn": "EradicationAndRecovery", "sv": "RecoveryService", "c": "Remediation", "dur": 72,
         "d": "Malware removal, system rebuilding, credential rotation, and vulnerability patching. AI validates eradication completeness before systems return to production.",
         "r": "Incomplete eradication means the attacker retains persistence. 25% of breaches see re-compromise within 90 days due to poor eradication.", "sub": [("MalwareRemoval", 24), ("SystemRebuilding", 24), ("CredentialRotation", 24)]},
        {"sn": "PostIncidentReview", "sv": "PIRService", "c": "Learning", "dur": 24,
         "d": "AI generates incident report, identifies root cause, and recommends security improvements. Detection rules updated. Tabletop exercises scheduled for similar scenarios.",
         "r": "Post-incident improvements prevent 70% of similar future attacks. Regulatory and insurance reporting requires detailed incident documentation.", "sub": [("RootCauseAnalysis", 8), ("DetectionTuning", 8), ("ReportGeneration", 8)]}
    ],
    "af": {
        "orderTotal": 150000, "transactionValue": 150000, "averageOrderValue": 120000,
        "contractValue": 500000, "annualRevenue": 35000000, "revenuePerCustomer": 280000,
        "profitMargin": 42.0, "customerLifetimeValue": 2200000, "lifetimeValue": 2200000,
        "acquisitionCost": 25000, "costPerAcquisition": 25000, "conversionProbability": 0.52,
        "conversionRate": 52, "engagementScore": 90, "timeToConversion": 720,
        "sessionDuration": 1800, "pageViews": 12, "purchaseFrequency": 12,
        "netPromoterScore": 55, "satisfactionRating": 4.4, "retentionProbability": 0.92,
        "processingTime": 5, "operationalCost": 35000, "efficiencyRating": 90,
        "mttd": 0.5, "mttr": 4.2,
        "channel": ["SOC_console", "SIEM_dashboard", "mobile_alert", "slack_integration", "email_escalation"],
        "deviceType": ["desktop", "desktop", "mobile", "desktop", "mobile"],
        "region": ["US East", "EU West", "APAC", "Middle East", "LATAM"],
        "customerSegmentValue": ["enterprise", "mid_market", "government", "financial_services", "healthcare"],
        "loyaltyTier": ["Platinum MDR", "Gold MDR", "Silver MDR", "Bronze", "IR Retainer"],
        "segment": ["ransomware", "APT", "insider_threat", "supply_chain", "phishing"],
        "Productname": ["Ransomware Response Package", "APT Hunt & Respond", "Insider Threat Investigation", "Supply Chain Breach", "BEC Response"],
        "ProductId": ["CYB-RW-001", "CYB-AP-002", "CYB-IT-003", "CYB-SC-004", "CYB-BC-005"],
        "ProductType": ["incident_response", "threat_hunting", "investigation", "breach_response", "fraud_response"],
        "Price": [150000, 250000, 100000, 200000, 75000],
        "threatSeverity": ["critical", "high", "medium", "critical", "high"],
        "attackVector": ["email_phish", "zero_day_exploit", "credential_theft", "supply_chain", "social_engineering"],
        "marketTrend": ["AI_SOC_automation", "XDR_convergence", "zero_trust", "cloud_native_security", "attack_surface_management"]
    }
},
"config-cybersecurity-threat-detection.json": {
    "co": "CyberShield Security", "dom": "https://www.cybershield-security.com",
    "ind": "Cybersecurity", "jt": "Threat Detection",
    "jd": "AI-Powered Continuous Threat Detection & Hunting",
    "steps": [
        {"sn": "DataIngestion", "sv": "DataIngestionService", "c": "Collection", "dur": 0.01,
         "d": "Real-time log collection from endpoints, network devices, cloud workloads, SaaS apps, and identity providers. 50TB+/day normalised and indexed.",
         "r": "Complete data coverage is foundational. Blind spots in telemetry are where attackers hide. Missing one log source can mean missing an entire attack chain.", "sub": [("EndpointTelemetry", 0.005), ("NetworkFlow", 0.003), ("CloudAudit", 0.002)]},
        {"sn": "BehaviourBaselining", "sv": "BaselineService", "c": "Analysis", "dur": 720,
         "d": "AI establishes normal behavior baselines for users, devices, and applications. UEBA models learn access patterns, data flows, and operational rhythms.",
         "r": "Behaviour baselines enable detection of novel attacks without signatures. Insider threats and compromised credentials are invisible to signature-based detection.", "sub": [("UserBaseline", 240), ("DeviceBaseline", 240), ("ApplicationBaseline", 240)]},
        {"sn": "RuleAndMLDetection", "sv": "DetectionEngineService", "c": "Detection", "dur": 0.02,
         "d": "Combination of expert-written detection rules (SIGMA/YARA) and ML models. Detects known TTPs, anomalous behavior, and emerging threats. 200+ MITRE ATT&CK techniques covered.",
         "r": "Layered detection catches 95% of attacks vs 60% for rules-only or ML-only. MITRE ATT&CK coverage is the industry benchmark.", "sub": [("RuleEngine", 0.005), ("MLDetection", 0.01), ("CorrelationEngine", 0.005)]},
        {"sn": "ThreatHunting", "sv": "HuntingService", "c": "Proactive", "dur": 40,
         "d": "AI-guided hypothesis-driven threat hunting. Identifies previously undetected compromises by analysing historical data against new threat intelligence.",
         "r": "Threat hunting discovers 20-30% more breaches than automated detection alone. Average dwell time for undiscovered breaches is 204 days.", "sub": [("HypothesisGeneration", 12), ("DataExploration", 16), ("FindingsValidation", 12)]},
        {"sn": "ThreatIntelligence", "sv": "ThreatIntelService", "c": "Intelligence", "dur": 24,
         "d": "AI aggregates and correlates threat intelligence from commercial feeds, OSINT, dark web monitoring, and industry ISACs. IOCs automatically deployed to detection stack.",
         "r": "Threat intelligence provides early warning of targeted attacks. Organisations with mature threat intel detect breaches 50% faster.", "sub": [("FeedAggregation", 8), ("IOCEnrichment", 8), ("AutoDeployment", 8)]},
        {"sn": "DetectionPerformance", "sv": "PerformanceService", "c": "Analytics", "dur": 168,
         "d": "AI measures detection coverage, false positive rates, MTTD, and MTTR trends. Gap analysis against MITRE ATT&CK framework. Detection engineering prioritisation.",
         "r": "Measuring detection performance drives continuous improvement. Organisations that track MITRE coverage improve detection rates by 25% annually.", "sub": [("CoverageAnalysis", 56), ("FPReduction", 56), ("GapPrioritisation", 56)]}
    ],
    "af": {
        "orderTotal": 200000, "transactionValue": 200000, "averageOrderValue": 180000,
        "contractValue": 600000, "annualRevenue": 35000000, "revenuePerCustomer": 350000,
        "profitMargin": 45.0, "customerLifetimeValue": 2800000, "lifetimeValue": 2800000,
        "acquisitionCost": 30000, "costPerAcquisition": 30000, "conversionProbability": 0.48,
        "conversionRate": 48, "engagementScore": 85, "timeToConversion": 1440,
        "sessionDuration": 2400, "pageViews": 15, "purchaseFrequency": 12,
        "netPromoterScore": 52, "satisfactionRating": 4.3, "retentionProbability": 0.90,
        "processingTime": 0.02, "operationalCost": 45000, "efficiencyRating": 88,
        "eventsPerSecond": 50000, "falsePositiveRate": 2.8,
        "channel": ["SIEM_console", "SOAR_playbook", "analyst_workbench", "API_integration", "threat_feed"],
        "deviceType": ["desktop", "desktop", "desktop", "server", "desktop"],
        "region": ["US", "UK", "Germany", "Japan", "Australia"],
        "customerSegmentValue": ["banking", "healthcare", "retail", "government", "tech"],
        "loyaltyTier": ["Enterprise SOC", "Managed SOC", "Co-Managed", "DIY", "MSSP"],
        "segment": ["endpoint", "network", "cloud", "identity", "email"],
        "Productname": ["EDR Platform", "NDR Sensor Network", "Cloud SIEM", "Identity Threat Detection", "Email Security Gateway"],
        "ProductId": ["DET-ED-001", "DET-ND-002", "DET-CS-003", "DET-ID-004", "DET-EM-005"],
        "ProductType": ["EDR", "NDR", "SIEM", "ITDR", "email_security"],
        "Price": [200000, 150000, 300000, 120000, 80000],
        "detectionCoverage": [0.85, 0.78, 0.92, 0.72, 0.88],
        "mitreAttackCoverage": [145, 120, 180, 95, 60],
        "marketTrend": ["XDR_platform", "AI_SOC_analyst", "cloud_native_SIEM", "identity_first_security", "purple_teaming"]
    }
},
"config-datacentre-capacity-planning.json": {
    "co": "DataCore Infrastructure", "dom": "https://www.datacore-infrastructure.com",
    "ind": "Data Centre & Cloud Infrastructure", "jt": "Capacity Planning",
    "jd": "AI-Driven Data Centre Capacity Management",
    "steps": [
        {"sn": "DemandForecasting", "sv": "DemandForecastService", "c": "Analysis", "dur": 48,
         "d": "AI predicts compute, storage, and network demand 6-18 months ahead using workload trends, customer pipeline, and seasonal patterns. GPU/AI workload demand modelled separately.",
         "r": "Data centre construction takes 18-24 months. Inaccurate forecasting means either stranded capital ($50M+/facility) or lost revenue from capacity shortfall.", "sub": [("WorkloadTrending", 16), ("PipelineAnalysis", 16), ("SeasonalModelling", 16)]},
        {"sn": "PowerAndCoolingDesign", "sv": "InfraDesignService", "c": "Design", "dur": 240,
         "d": "AI optimises power distribution, cooling architecture, and rack density. PUE targets set and modelled. Renewable energy integration planned.",
         "r": "Power and cooling are 40% of data centre operating cost. A 0.1 PUE improvement on a 20MW facility saves $1.5M/year.", "sub": [("PowerDesign", 80), ("CoolingArchitecture", 80), ("RenewableIntegration", 80)]},
        {"sn": "RackAndFloorPlanning", "sv": "FloorPlanService", "c": "Layout", "dur": 72,
         "d": "AI optimises rack placement, hot/cold aisle containment, and cable pathways. Weight loading, fire suppression zones, and maintenance access considered.",
         "r": "Optimal floor planning increases usable capacity by 15-20%. Poor airflow management wastes 25% of cooling energy.", "sub": [("RackPlacement", 24), ("AirflowModelling", 24), ("CablePathway", 24)]},
        {"sn": "ProcurementAndInstallation", "sv": "ProcurementService", "c": "Execution", "dur": 720,
         "d": "AI manages server, switch, and storage procurement. Vendor comparison, delivery scheduling, and installation sequencing optimised. Commissioning testing automated.",
         "r": "Lead times for servers are 12-26 weeks. Optimal procurement timing and vendor diversification prevents $10M+ in delayed revenue.", "sub": [("VendorSelection", 240), ("DeliveryScheduling", 240), ("Commissioning", 240)]},
        {"sn": "CapacityMonitoring", "sv": "CapacityMonitorService", "c": "Operations", "dur": 8760,
         "d": "Real-time monitoring of power draw, cooling efficiency, rack utilisation, and network bandwidth. AI alerts on capacity thresholds and efficiency degradation.",
         "r": "Real-time monitoring prevents overloading (which causes outages) and identifies underutilised capacity for reallocation.", "sub": [("PowerMonitoring", 2920), ("CoolingEfficiency", 2920), ("UtilisationTracking", 2920)]},
        {"sn": "CapacityOptimization", "sv": "OptimizationService", "c": "Optimization", "dur": 168,
         "d": "AI recommends workload migration, server refresh, and decommissioning. Stranded capacity recovered. Carbon footprint and energy cost optimised.",
         "r": "Ongoing optimisation recovers 10-15% of stranded capacity. Server refresh at optimal time improves performance/watt by 30-50%.", "sub": [("WorkloadMigration", 56), ("RefreshPlanning", 56), ("CarbonOptimization", 56)]}
    ],
    "af": {
        "orderTotal": 5000000, "transactionValue": 5000000, "averageOrderValue": 3500000,
        "contractValue": 50000000, "annualRevenue": 800000000, "revenuePerCustomer": 12000000,
        "profitMargin": 28.0, "customerLifetimeValue": 120000000, "lifetimeValue": 120000000,
        "acquisitionCost": 500000, "costPerAcquisition": 500000, "conversionProbability": 0.65,
        "conversionRate": 65, "engagementScore": 80, "timeToConversion": 8640,
        "sessionDuration": 3600, "pageViews": 20, "purchaseFrequency": 2,
        "netPromoterScore": 50, "satisfactionRating": 4.1, "retentionProbability": 0.92,
        "processingTime": 43200, "operationalCost": 2000000, "efficiencyRating": 82,
        "pueTarget": 1.2, "totalPowerMW": 20,
        "channel": ["sales_portal", "partner_portal", "RFP_response", "direct_sales", "marketplace"],
        "deviceType": ["desktop", "desktop", "desktop", "desktop", "mobile"],
        "region": ["Virginia US", "Frankfurt DE", "Singapore", "London", "Mumbai"],
        "customerSegmentValue": ["hyperscaler", "enterprise", "government", "colocation", "edge"],
        "loyaltyTier": ["Strategic", "Enterprise", "Growth", "Standard", "Edge"],
        "segment": ["colocation", "managed_hosting", "cloud_infrastructure", "GPU_compute", "edge_compute"],
        "Productname": ["Enterprise Colocation Suite", "GPU Cluster Build", "Edge Micro-DC", "Managed Hosting Platform", "Disaster Recovery Site"],
        "ProductId": ["DC-CL-001", "DC-GP-002", "DC-ED-003", "DC-MH-004", "DC-DR-005"],
        "ProductType": ["colocation", "GPU_hosting", "edge", "managed", "DR"],
        "Price": [50000000, 25000000, 5000000, 15000000, 8000000],
        "rackCount": [500, 200, 20, 150, 80],
        "uptime": [99.999, 99.99, 99.95, 99.99, 99.999],
        "marketTrend": ["AI_DC_demand", "liquid_cooling", "nuclear_power", "edge_computing", "sustainable_DC"]
    }
},
"config-datacentre-cooling-optimization.json": {
    "co": "DataCore Infrastructure", "dom": "https://www.datacore-infrastructure.com",
    "ind": "Data Centre & Cloud Infrastructure", "jt": "Cooling Optimization",
    "jd": "AI-Powered Data Centre Cooling Efficiency",
    "steps": [
        {"sn": "ThermalMapping", "sv": "ThermalMappingService", "c": "Assessment", "dur": 48,
         "d": "AI creates 3D thermal map of data centre from thousands of temperature sensors and CFD modelling. Hotspots, cold spots, and air recirculation identified.",
         "r": "Thermal mapping reveals that 30% of cooling energy is wasted on over-cooled areas while hotspots throttle servers. Fixing this distribution saves 15-25% of cooling costs.", "sub": [("SensorDeployment", 16), ("CFDModelling", 16), ("HotspotIdentification", 16)]},
        {"sn": "AirflowOptimization", "sv": "AirflowService", "c": "Optimization", "dur": 72,
         "d": "AI adjusts CRAC/CRAH unit settings, variable-speed fan drives, and blanking panel placement. Hot/cold aisle containment effectiveness measured and improved.",
         "r": "Optimised airflow reduces cooling energy by 20-30%. Each degree of supply air temperature increase saves 2-5% of cooling energy.", "sub": [("CRACOptimization", 24), ("FanSpeedControl", 24), ("ContainmentImprovement", 24)]},
        {"sn": "FreeCooltingMaximization", "sv": "FreeCoolingService", "c": "Efficiency", "dur": 8760,
         "d": "AI maximises free cooling economiser hours by predicting weather and adjusting switchover points. Dew point control prevents condensation during humid conditions.",
         "r": "Free cooling can reduce mechanical refrigeration by 50-70% in temperate climates. Each additional free cooling hour saves significant compressor energy.", "sub": [("WeatherPrediction", 2920), ("EconomiserControl", 2920), ("DewPointManagement", 2920)]},
        {"sn": "LiquidCoolingIntegration", "sv": "LiquidCoolingService", "c": "Innovation", "dur": 480,
         "d": "AI manages direct-to-chip liquid cooling for high-density GPU racks. Coolant flow, temperature, and pressure monitored. Heat reuse for district heating evaluated.",
         "r": "GPU racks at 50-100kW need liquid cooling. Air cooling fails above 25kW/rack. Liquid cooling enables the AI workload revenue stream.", "sub": [("FlowOptimization", 160), ("TemperatureControl", 160), ("HeatReuse", 160)]},
        {"sn": "PUETracking", "sv": "PUETrackingService", "c": "Monitoring", "dur": 8760,
         "d": "Real-time PUE measurement at facility, floor, and row level. AI identifies PUE degradation causes and recommends corrective actions. Benchmarked against industry peers.",
         "r": "PUE is the primary DC efficiency KPI. Reducing PUE from 1.4 to 1.2 on a 20MW facility saves $3M/year. Investor ESG reporting requires PUE disclosure.", "sub": [("RealTimePUE", 2920), ("DegradationAnalysis", 2920), ("BenchmarkReporting", 2920)]},
        {"sn": "PredictiveMaintenance", "sv": "CoolingMaintenanceService", "c": "Maintenance", "dur": 168,
         "d": "AI predicts chiller, pump, and cooling tower failures from vibration, refrigerant pressure, and performance degradation. Maintenance scheduled to avoid hot weather periods.",
         "r": "Chiller failure during a heat wave can cause facility-wide outage. Each hour of cooling failure risks $1M+ in SLA penalties and customer churn.", "sub": [("ChillerHealth", 56), ("PumpMonitoring", 56), ("TowerPerformance", 56)]}
    ],
    "af": {
        "orderTotal": 2000000, "transactionValue": 2000000, "averageOrderValue": 1500000,
        "contractValue": 8000000, "annualRevenue": 800000000, "revenuePerCustomer": 12000000,
        "profitMargin": 28.0, "customerLifetimeValue": 120000000, "lifetimeValue": 120000000,
        "acquisitionCost": 100000, "costPerAcquisition": 100000, "conversionProbability": 0.85,
        "conversionRate": 85, "engagementScore": 82, "timeToConversion": 2160,
        "sessionDuration": 1800, "pageViews": 10, "purchaseFrequency": 4,
        "netPromoterScore": 48, "satisfactionRating": 4.0, "retentionProbability": 0.95,
        "processingTime": 720, "operationalCost": 1500000, "efficiencyRating": 80,
        "currentPUE": 1.35, "targetPUE": 1.15,
        "channel": ["BMS_dashboard", "DCIM_platform", "mobile_app", "API_feed", "IoT_sensor"],
        "deviceType": ["desktop", "desktop", "mobile", "server", "sensor"],
        "region": ["Virginia US", "Dublin IE", "Singapore", "Oslo NO", "Tokyo JP"],
        "customerSegmentValue": ["hyperscaler", "enterprise_colo", "government", "telco", "financial"],
        "loyaltyTier": ["Platinum", "Gold", "Silver", "Bronze", "Standard"],
        "segment": ["air_cooling", "liquid_cooling", "free_cooling", "heat_reuse", "hybrid"],
        "Productname": ["Rear Door Heat Exchanger", "Direct-to-Chip CDU", "Adiabatic Economiser", "Immersion Cooling Tank", "AI Cooling Controller"],
        "ProductId": ["COL-RD-001", "COL-DC-002", "COL-AE-003", "COL-IM-004", "COL-AI-005"],
        "ProductType": ["heat_exchanger", "liquid_cooling", "free_cooling", "immersion", "controller"],
        "Price": [2000000, 5000000, 1500000, 3000000, 500000],
        "coolingCapacityKW": [500, 200, 800, 100, 0],
        "energySavings": [0.15, 0.30, 0.45, 0.35, 0.10],
        "marketTrend": ["liquid_cooling", "AI_thermal_management", "heat_reuse", "nuclear_powered_DC", "underwater_DC"]
    }
},
"config-delivery-dispatch-optimization.json": {
    "co": "SwiftDeliver Logistics", "dom": "https://www.swiftdeliver.com",
    "ind": "Last-Mile Delivery", "jt": "Dispatch Optimization",
    "jd": "AI-Powered Last-Mile Dispatch & Routing",
    "steps": [
        {"sn": "OrderBatching", "sv": "OrderBatchService", "c": "Planning", "dur": 0.5,
         "d": "AI groups orders into optimal delivery batches based on location proximity, time windows, package size, and vehicle capacity. Dynamic re-batching as new orders arrive.",
         "r": "Optimal batching reduces delivery cost per parcel by 25-35%. Poor batching means half-empty vehicles and missed delivery windows.", "sub": [("ProximityGrouping", 0.2), ("TimeWindowFit", 0.15), ("CapacityOptimization", 0.15)]},
        {"sn": "RouteOptimization", "sv": "RouteService", "c": "Routing", "dur": 0.25,
         "d": "AI calculates optimal delivery routes considering traffic, road restrictions, driver hours, and customer preferences. Real-time re-routing around congestion and incidents.",
         "r": "Route optimization reduces total distance by 20-30% and fuel costs by 15-25%. Each unnecessary km costs $0.50 in fuel and vehicle wear.", "sub": [("TrafficPrediction", 0.1), ("ConstraintSolving", 0.1), ("DynamicRerouting", 0.05)]},
        {"sn": "DriverAssignment", "sv": "DriverAssignService", "c": "Allocation", "dur": 0.1,
         "d": "AI assigns drivers to routes based on skills, vehicle type, area familiarity, and working hours compliance. Gig driver surge pricing managed.",
         "r": "Right driver-route matching improves delivery success rate from 92% to 98%. Wrong vehicle type for the area causes failed deliveries.", "sub": [("SkillMatching", 0.04), ("HoursCompliance", 0.03), ("SurgePricing", 0.03)]},
        {"sn": "RealTimeTracking", "sv": "TrackingService", "c": "Monitoring", "dur": 480,
         "d": "GPS tracking with AI-predicted ETAs updated every 2 minutes. Customer notifications at key milestones. Anomaly detection for route deviations and long stop times.",
         "r": "Accurate ETAs reduce 'Where is my order?' calls by 60%. Real-time tracking is now a baseline customer expectation.", "sub": [("GPSTracking", 160), ("ETAPrediction", 160), ("AnomalyDetection", 160)]},
        {"sn": "DeliveryExecution", "sv": "DeliveryExecService", "c": "Fulfilment", "dur": 2,
         "d": "AI-guided delivery: photo proof, signature capture, safe place recommendations, and age verification. Failed delivery alternatives offered in real-time.",
         "r": "First-attempt delivery success over 95% is critical. Each failed delivery costs $8-15 in re-delivery and customer service.", "sub": [("ProofCapture", 0.5), ("AgeVerification", 0.5), ("FailedDeliveryHandling", 1)]},
        {"sn": "PerformanceAnalytics", "sv": "DeliveryAnalyticsService", "c": "Analytics", "dur": 24,
         "d": "AI analyses delivery success rates, driver performance, customer satisfaction, and cost per delivery. Continuous route and process improvement recommendations.",
         "r": "Data-driven optimization reduces cost per delivery by 5-10% quarter over quarter. Identifying underperforming routes saves $100K+ annually.", "sub": [("SuccessRateAnalysis", 8), ("DriverScorecard", 8), ("CostOptimization", 8)]}
    ],
    "af": {
        "orderTotal": 8.50, "transactionValue": 8.50, "averageOrderValue": 45,
        "contractValue": 0, "annualRevenue": 250000000, "revenuePerCustomer": 120,
        "profitMargin": 5.0, "customerLifetimeValue": 850, "lifetimeValue": 850,
        "acquisitionCost": 12, "costPerAcquisition": 12, "conversionProbability": 0.95,
        "conversionRate": 95, "engagementScore": 72, "timeToConversion": 1,
        "sessionDuration": 60, "pageViews": 3, "purchaseFrequency": 24,
        "netPromoterScore": 35, "satisfactionRating": 3.8, "retentionProbability": 0.72,
        "processingTime": 15, "operationalCost": 4.50, "efficiencyRating": 82,
        "deliverySuccessRate": 96.5, "avgDeliveryTime": 35,
        "channel": ["ecommerce_API", "marketplace_integration", "mobile_app", "web_booking", "phone_order"],
        "deviceType": ["server", "server", "mobile", "desktop", "phone"],
        "region": ["London", "Manchester", "Birmingham", "Leeds", "Glasgow"],
        "customerSegmentValue": ["ecommerce_retailer", "grocery_chain", "restaurant", "pharmacy", "DTC_brand"],
        "loyaltyTier": ["Enterprise", "Growth", "Standard", "On-Demand", "Marketplace"],
        "segment": ["same_day", "next_day", "standard", "grocery", "bulky"],
        "Productname": ["Same-Day Express", "Next-Day Standard", "Grocery Fresh", "Bulky Item Delivery", "Returns Collection"],
        "ProductId": ["DEL-SD-001", "DEL-ND-002", "DEL-GR-003", "DEL-BK-004", "DEL-RT-005"],
        "ProductType": ["express", "standard", "temperature_controlled", "two_person", "reverse_logistics"],
        "Price": [12.50, 5.99, 3.99, 29.99, 0],
        "parcelsPerDay": [25000, 80000, 15000, 3000, 8000],
        "vehicleType": ["van", "van", "refrigerated_van", "luton", "car"],
        "marketTrend": ["autonomous_delivery", "drone_delivery", "micro_fulfilment", "green_fleet", "crowd_sourced_delivery"]
    }
},
"config-delivery-eta-prediction.json": {
    "co": "SwiftDeliver Logistics", "dom": "https://www.swiftdeliver.com",
    "ind": "Last-Mile Delivery", "jt": "ETA Prediction",
    "jd": "AI-Powered Delivery ETA Accuracy",
    "steps": [
        {"sn": "DataCollection", "sv": "DataCollectionService", "c": "Ingestion", "dur": 0.01,
         "d": "Real-time data collection from GPS trackers, traffic APIs, weather services, and historical delivery records. 100M+ data points processed daily for ETA model training.",
         "r": "ETA model accuracy depends on data completeness. Missing traffic data causes 15-minute average ETA errors during peak hours.", "sub": [("GPSIngestion", 0.005), ("TrafficFeed", 0.003), ("WeatherIntegration", 0.002)]},
        {"sn": "ModelTraining", "sv": "MLModelService", "c": "ML", "dur": 480,
         "d": "AI trains ETA models using gradient boosting and deep learning on historical deliveries. Features include: time of day, day of week, weather, traffic, driver, area, and package type.",
         "r": "Model accuracy improves delivery satisfaction scores by 15-20 points. A 5-minute ETA improvement reduces missed deliveries by 8%.", "sub": [("FeatureEngineering", 160), ("ModelTraining", 160), ("ValidationTesting", 160)]},
        {"sn": "RealTimeInference", "sv": "InferenceService", "c": "Prediction", "dur": 0.05,
         "d": "AI calculates ETA for every active delivery every 2 minutes. Factors live traffic, driver speed, remaining stops, and parking difficulty. Confidence intervals provided.",
         "r": "Real-time ETA updates reduce customer anxiety and 'where is my order' contacts by 40%. Confidence intervals set realistic expectations.", "sub": [("ContextAssembly", 0.02), ("ModelInference", 0.02), ("ConfidenceCalc", 0.01)]},
        {"sn": "NotificationEngine", "sv": "NotificationService", "c": "Communication", "dur": 0.5,
         "d": "AI triggers customer notifications at optimal times: order dispatched, driver nearby, arriving in 10 minutes, delivered. Channel preference respected.",
         "r": "Well-timed notifications reduce failed deliveries by 12% (customer is prepared). Over-notification causes opt-out. AI balances helpfulness vs annoyance.", "sub": [("TriggerLogic", 0.2), ("ChannelSelection", 0.15), ("MessagePersonalisation", 0.15)]},
        {"sn": "AccuracyMonitoring", "sv": "AccuracyService", "c": "Monitoring", "dur": 24,
         "d": "AI monitors ETA prediction accuracy by region, time window, driver, and delivery type. Model drift detected and automatic retraining triggered.",
         "r": "ETA model accuracy degrades 1-2% per month without retraining. Monitoring ensures consistent customer experience across seasons and events.", "sub": [("AccuracyTracking", 8), ("DriftDetection", 8), ("RetrainingTrigger", 8)]},
        {"sn": "ContinuousImprovement", "sv": "ETAImprovementService", "c": "Optimization", "dur": 168,
         "d": "AI analyses systematic ETA errors by area, building type, and time of day. Parking difficulty indices learned. Business rules refined for edge cases.",
         "r": "Systematic error analysis improves ETA accuracy from 80% to 92% within ±5 minutes. Edge case handling prevents the worst customer experiences.", "sub": [("ErrorPatternAnalysis", 56), ("ParkingDifficultyLearning", 56), ("EdgeCaseRefinement", 56)]}
    ],
    "af": {
        "orderTotal": 8.50, "transactionValue": 8.50, "averageOrderValue": 45,
        "contractValue": 500000, "annualRevenue": 250000000, "revenuePerCustomer": 120,
        "profitMargin": 5.0, "customerLifetimeValue": 850, "lifetimeValue": 850,
        "acquisitionCost": 12, "costPerAcquisition": 12, "conversionProbability": 0.95,
        "conversionRate": 95, "engagementScore": 78, "timeToConversion": 1,
        "sessionDuration": 30, "pageViews": 2, "purchaseFrequency": 24,
        "netPromoterScore": 42, "satisfactionRating": 4.0, "retentionProbability": 0.75,
        "processingTime": 0.05, "operationalCost": 0.01, "efficiencyRating": 88,
        "etaAccuracy": 91.5, "avgETAError": 4.2,
        "channel": ["customer_app", "SMS", "email", "push_notification", "web_tracker"],
        "deviceType": ["mobile", "mobile", "desktop", "mobile", "desktop"],
        "region": ["London", "New York", "Berlin", "Tokyo", "Sydney"],
        "customerSegmentValue": ["prime_subscriber", "regular", "business", "first_time", "marketplace"],
        "loyaltyTier": ["Prime", "Plus", "Standard", "Trial", "Guest"],
        "segment": ["same_day", "next_day", "scheduled", "instant", "click_and_collect"],
        "Productname": ["Same-Day ETA Widget", "Next-Day Tracker", "Live Map Tracker", "10min Alert Service", "Delivery Window Selector"],
        "ProductId": ["ETA-SD-001", "ETA-ND-002", "ETA-LM-003", "ETA-AL-004", "ETA-DW-005"],
        "ProductType": ["widget", "tracker", "map", "alert", "scheduler"],
        "Price": [0, 0, 0, 0, 0],
        "predictionWindow": [30, 120, 5, 10, 60],
        "accuracyTarget": [0.90, 0.92, 0.95, 0.85, 0.88],
        "marketTrend": ["real_time_visibility", "predictive_logistics", "autonomous_delivery_ETA", "crowd_ETA_learning", "carbon_aware_routing"]
    }
},
}

if __name__ == "__main__":
    for fn, data in SECTORS.items():
        gen(fn, data)
    print(f"Batch 3 complete: {len(SECTORS)} configs updated.")
