#!/usr/bin/env python3
"""Batch 4: esg, ev, fashion, fitness"""
import json, os, uuid

CONFIGS_DIR = os.path.join(os.path.dirname(__file__), '..', 'saved-configs')

def gen(fn, d):
    steps = []
    for i, s in enumerate(d["steps"], 1):
        st = {"stepIndex": i, "stepName": s["sn"], "serviceName": s["sv"], "description": s["d"],
              "category": s["c"], "estimatedDuration": s["dur"], "businessRationale": s["r"],
              "substeps": [{"substepName": n, "duration": dur} for n, dur in s["sub"]]}
        if i == 1: st["timestamp"] = "2025-11-21T00:00:00.000Z"
        steps.append(st)
    config = {"companyName": d["co"], "domain": d["dom"], "industryType": d["ind"],
              "journeyType": d["jt"], "journeyDetail": d["jd"],
              "journeyId": f"journey_{d['jt'].lower().replace(' ','_')}_{uuid.uuid4().hex[:8]}",
              "journeyStartTime": "2025-11-21T00:00:00.000Z", "steps": steps,
              "id": str(uuid.uuid4()), "name": f"{d['ind']} - {d['jt']}",
              "timestamp": "2026-03-18T12:00:00.000Z", "source": "sector-demo",
              "additionalFields": d["af"]}
    with open(os.path.join(CONFIGS_DIR, fn), 'w') as f: json.dump(config, f, indent=4)
    print(f"  ✅ {fn}")

SECTORS = {
"config-esg-carbon-tracking.json": {
    "co": "GreenMetrics ESG", "dom": "https://www.greenmetrics-esg.com",
    "ind": "ESG & Sustainability", "jt": "Carbon Tracking",
    "jd": "AI-Powered Carbon Footprint Management",
    "steps": [
        {"sn": "EmissionsDataCollection", "sv": "EmissionsDataService", "c": "Ingestion", "dur": 48,
         "d": "AI auto-collects Scope 1 (direct), Scope 2 (energy), and Scope 3 (supply chain) emissions data from ERP, utility bills, travel systems, and supplier questionnaires.",
         "r": "Scope 3 emissions are 75% of total but hardest to measure. Incomplete data means inaccurate reporting and greenwashing risk.", "sub": [("Scope1Collection", 12), ("Scope2Collection", 12), ("Scope3Estimation", 24)]},
        {"sn": "CarbonCalculation", "sv": "CarbonCalcService", "c": "Calculation", "dur": 24,
         "d": "AI calculates carbon footprint using GHG Protocol methodology. Emission factors applied per activity and region. Uncertainty analysis and data quality scoring.",
         "r": "Regulatory penalties for inaccurate carbon reporting are increasing globally. The EU CSRD requires audited carbon disclosures.", "sub": [("FactorSelection", 8), ("FootprintCalculation", 8), ("UncertaintyAnalysis", 8)]},
        {"sn": "ReductionPathway", "sv": "PathwayService", "c": "Strategy", "dur": 72,
         "d": "AI models decarbonisation pathways aligned with SBTi targets. Cost-benefit analysis of reduction initiatives: renewable energy, electrification, supply chain engagement.",
         "r": "Companies with credible reduction plans attract 15-20% valuation premium. SBTi-aligned targets are becoming mandatory for large enterprises.", "sub": [("SBTiAlignment", 24), ("InitiativeModelling", 24), ("CostBenefitAnalysis", 24)]},
        {"sn": "OffsetManagement", "sv": "OffsetService", "c": "Procurement", "dur": 48,
         "d": "AI evaluates carbon credit quality, permanence, and additionality. Portfolio of offsets managed across registries. Retirement scheduling aligned with reporting periods.",
         "r": "Low-quality offsets face reputational and regulatory risk. AI quality scoring prevents investment in offsets that may be invalidated.", "sub": [("CreditEvaluation", 16), ("PortfolioManagement", 16), ("RetirementScheduling", 16)]},
        {"sn": "RegulatoryReporting", "sv": "ReportingService", "c": "Compliance", "dur": 72,
         "d": "AI auto-generates reports for CDP, TCFD, CSRD, SEC Climate, and GRI Standards. Multi-jurisdictional reporting from single data set. Audit trail maintained.",
         "r": "Regulatory reporting is now mandatory in EU, UK, and incoming in US. Non-compliance fines range from $100K to $1M+ and investor exclusion.", "sub": [("CDPSubmission", 24), ("CSRDCompliance", 24), ("SECClimateReporting", 24)]},
        {"sn": "StakeholderDashboard", "sv": "DashboardService", "c": "Communication", "dur": 24,
         "d": "AI generates real-time carbon dashboards for board, investors, and operational teams. Progress against targets visualised. Peer benchmarking and industry ranking.",
         "r": "Transparent carbon communication improves ESG ratings (MSCI, Sustainalytics) which directly affects cost of capital and investor allocation.", "sub": [("BoardDashboard", 8), ("InvestorReporting", 8), ("PeerBenchmarking", 8)]}
    ],
    "af": {
        "orderTotal": 150000, "transactionValue": 150000, "averageOrderValue": 120000,
        "contractValue": 400000, "annualRevenue": 15000000, "revenuePerCustomer": 250000,
        "profitMargin": 55.0, "customerLifetimeValue": 1500000, "lifetimeValue": 1500000,
        "acquisitionCost": 20000, "costPerAcquisition": 20000, "conversionProbability": 0.48,
        "conversionRate": 48, "engagementScore": 82, "timeToConversion": 2880,
        "sessionDuration": 2400, "pageViews": 18, "purchaseFrequency": 4,
        "netPromoterScore": 52, "satisfactionRating": 4.3, "retentionProbability": 0.88,
        "processingTime": 4320, "operationalCost": 35000, "efficiencyRating": 78,
        "totalEmissionsTonnes": 125000, "reductionTarget": 42,
        "channel": ["ESG_platform", "supplier_portal", "API_integration", "consultant_portal", "board_dashboard"],
        "deviceType": ["desktop", "desktop", "server", "desktop", "tablet"],
        "region": ["EU", "North America", "UK", "APAC", "Middle East"],
        "customerSegmentValue": ["large_enterprise", "mid_market", "financial_institution", "government", "PE_fund"],
        "loyaltyTier": ["Enterprise", "Professional", "Standard", "Starter", "Trial"],
        "segment": ["carbon_accounting", "CSRD_compliance", "supply_chain_emissions", "offset_management", "climate_risk"],
        "Productname": ["Scope 3 Supplier Engine", "CSRD Reporting Module", "SBTi Pathway Builder", "Carbon Credit Marketplace", "TCFD Risk Assessment"],
        "ProductId": ["ESG-S3-001", "ESG-CS-002", "ESG-SB-003", "ESG-CC-004", "ESG-TC-005"],
        "ProductType": ["scope3_tool", "reporting", "strategy", "marketplace", "risk_assessment"],
        "Price": [200000, 150000, 100000, 50000, 120000],
        "emissionIntensity": [0.45, 0.32, 0.68, 0.22, 0.55],
        "dataQualityScore": [85, 78, 62, 90, 72],
        "marketTrend": ["CSRD_compliance", "scope3_automation", "carbon_credit_quality", "climate_risk_modelling", "biodiversity_reporting"]
    }
},
"config-esg-sustainability-reporting.json": {
    "co": "GreenMetrics ESG", "dom": "https://www.greenmetrics-esg.com",
    "ind": "ESG & Sustainability", "jt": "Sustainability Reporting",
    "jd": "AI-Automated ESG Sustainability Reporting",
    "steps": [
        {"sn": "MaterialityAssessment", "sv": "MaterialityService", "c": "Strategy", "dur": 240,
         "d": "AI performs double materiality assessment per CSRD requirements. Stakeholder surveys analysed. Impact and financial materiality mapped across ESG topics.",
         "r": "Double materiality is mandatory under CSRD. It determines which ESG topics require disclosure and drives the entire reporting scope.", "sub": [("StakeholderAnalysis", 80), ("ImpactMateriality", 80), ("FinancialMateriality", 80)]},
        {"sn": "DataAggregation", "sv": "DataAggregationService", "c": "Collection", "dur": 168,
         "d": "AI collects ESG data across environmental, social, and governance metrics from 50+ internal systems. Data validation, gap identification, and quality scoring.",
         "r": "ESG reporting requires 1000+ data points. Manual collection takes 3-6 months. AI reduces this to weeks with higher data quality.", "sub": [("EnvironmentalData", 56), ("SocialData", 56), ("GovernanceData", 56)]},
        {"sn": "FrameworkAlignment", "sv": "AlignmentService", "c": "Mapping", "dur": 48,
         "d": "AI maps data to multiple frameworks: GRI, SASB, CSRD/ESRS, TCFD, UN SDGs. Cross-framework reconciliation eliminates duplicate reporting effort.",
         "r": "Companies report to 3-5 frameworks. Manual mapping takes months. AI auto-alignment reduces effort by 70% and ensures consistency.", "sub": [("GRIMapping", 16), ("CSRDMapping", 16), ("CrossReconciliation", 16)]},
        {"sn": "ReportGeneration", "sv": "ReportGenService", "c": "Production", "dur": 72,
         "d": "AI drafts sustainability report narrative, creates data visualisations, and formats per framework requirements. Multi-language versions generated automatically.",
         "r": "Report production takes 4-8 weeks manually. AI-drafted narratives with human review reduce this to 1-2 weeks.", "sub": [("NarrativeDrafting", 24), ("DataVisualisation", 24), ("MultiLanguage", 24)]},
        {"sn": "AssurancePreparation", "sv": "AssuranceService", "c": "Audit", "dur": 168,
         "d": "AI prepares audit working papers, evidence packs, and data lineage documentation. Limited or reasonable assurance readiness assessed and gaps flagged.",
         "r": "CSRD requires third-party assurance on ESG reports. Audit-ready data reduces assurance costs by 30% and prevents qualified opinions.", "sub": [("EvidencePreparation", 56), ("DataLineage", 56), ("GapRemediation", 56)]},
        {"sn": "StakeholderDistribution", "sv": "DistributionService", "c": "Communication", "dur": 24,
         "d": "AI distributes reports to regulators, investors, rating agencies, and public. Filing with ESMA ESEF taxonomy. ESG rating agency questionnaire auto-filling.",
         "r": "Timely distribution to rating agencies improves ESG scores. MSCI/Sustainalytics ratings directly affect investor allocation and cost of capital.", "sub": [("RegulatoryFiling", 8), ("InvestorDistribution", 8), ("RatingAgencyFiling", 8)]}
    ],
    "af": {
        "orderTotal": 200000, "transactionValue": 200000, "averageOrderValue": 175000,
        "contractValue": 500000, "annualRevenue": 15000000, "revenuePerCustomer": 300000,
        "profitMargin": 55.0, "customerLifetimeValue": 1800000, "lifetimeValue": 1800000,
        "acquisitionCost": 25000, "costPerAcquisition": 25000, "conversionProbability": 0.52,
        "conversionRate": 52, "engagementScore": 85, "timeToConversion": 4320,
        "sessionDuration": 3600, "pageViews": 25, "purchaseFrequency": 4,
        "netPromoterScore": 55, "satisfactionRating": 4.4, "retentionProbability": 0.90,
        "processingTime": 10080, "operationalCost": 50000, "efficiencyRating": 80,
        "esgRating": "AA", "frameworkCount": 5,
        "channel": ["ESG_platform", "auditor_portal", "board_dashboard", "investor_portal", "regulator_filing"],
        "deviceType": ["desktop", "desktop", "tablet", "desktop", "desktop"],
        "region": ["EU", "UK", "US", "Japan", "Australia"],
        "customerSegmentValue": ["CSRD_obligated", "voluntary_reporter", "listed_company", "PE_portfolio", "government_entity"],
        "loyaltyTier": ["Enterprise", "Professional", "Standard", "Starter", "Trial"],
        "segment": ["CSRD_ESRS", "GRI", "TCFD", "SEC_Climate", "voluntary"],
        "Productname": ["CSRD Full Compliance Suite", "GRI Standards Reporting", "TCFD Climate Disclosure", "SEC Climate Rule Filing", "SDG Impact Report"],
        "ProductId": ["ESG-CR-001", "ESG-GR-002", "ESG-TF-003", "ESG-SC-004", "ESG-SD-005"],
        "ProductType": ["regulatory_compliance", "standards_reporting", "climate_disclosure", "SEC_filing", "impact_report"],
        "Price": [300000, 150000, 100000, 200000, 80000],
        "dataPointsReported": [1200, 800, 450, 350, 200],
        "assuranceLevel": ["reasonable", "limited", "limited", "reasonable", "none"],
        "marketTrend": ["CSRD_wave2", "AI_ESG_reporting", "interoperability_standards", "biodiversity_disclosure", "double_materiality"]
    }
},
"config-ev-charging-session.json": {
    "co": "ChargePoint Plus", "dom": "https://www.chargepointplus.com",
    "ind": "Electric Vehicle & Charging", "jt": "Charging Session",
    "jd": "AI-Optimised EV Charging Session Management",
    "steps": [
        {"sn": "StationDiscovery", "sv": "StationDiscoveryService", "c": "Search", "dur": 0.5,
         "d": "AI recommends nearest available chargers considering current charge level, destination, charger speed, pricing, and real-time availability. Route integrated charging planned.",
         "r": "Range anxiety is the #1 barrier to EV adoption. Reducing charger search time from 10 minutes to 30 seconds improves driver experience dramatically.", "sub": [("AvailabilityCheck", 0.2), ("PriceComparison", 0.15), ("RouteIntegration", 0.15)]},
        {"sn": "SessionInitiation", "sv": "SessionStartService", "c": "Authentication", "dur": 0.25,
         "d": "Plug-and-charge authentication via ISO 15118 or RFID/app. Payment method verified. Charging speed negotiated between vehicle and charger. Business event: session_started.",
         "r": "Frictionless start is critical — 15% of public charging attempts fail at authentication. Plug-and-charge eliminates the #1 driver complaint.", "sub": [("Authentication", 0.1), ("PaymentVerification", 0.1), ("SpeedNegotiation", 0.05)]},
        {"sn": "ChargingOptimization", "sv": "ChargingOptService", "c": "Execution", "dur": 30,
         "d": "AI manages charging power curve to maximise battery health while minimising charge time. Temperature monitoring and power sharing across multiple vehicles at the site.",
         "r": "Optimal charging extends battery life by 15-20% over aggressive fast charging. Power sharing prevents site breaker trips and ensures all vehicles charge.", "sub": [("PowerCurveManagement", 10), ("BatteryHealthProtection", 10), ("PowerSharing", 10)]},
        {"sn": "GridBalancing", "sv": "GridBalancingService", "c": "Energy", "dur": 30,
         "d": "AI balances EV charging demand against grid capacity, renewable energy availability, and time-of-use pricing. V2G bidirectional charging managed for grid services.",
         "r": "Smart charging reduces energy costs by 20-40%. V2G grid services can generate $500-1500/year per vehicle in ancillary service payments.", "sub": [("DemandResponse", 10), ("RenewableMatching", 10), ("V2GManagement", 10)]},
        {"sn": "SessionCompletion", "sv": "SessionCompleteService", "c": "Billing", "dur": 0.5,
         "d": "Session ended automatically at target SoC or manually. Energy delivered, time, and cost calculated. Receipt issued. Charger released for next user.",
         "r": "Accurate billing builds trust. Overstay management keeps chargers available — one blocked charger during peak costs $50-100/hour in lost revenue.", "sub": [("EnergyCalculation", 0.2), ("BillingGeneration", 0.2), ("OverstayManagement", 0.1)]},
        {"sn": "FleetReporting", "sv": "FleetReportService", "c": "Analytics", "dur": 24,
         "d": "AI generates fleet charging reports: energy consumed, cost per mile, CO2 avoided, and charger utilisation. Anomaly detection flags faulty chargers and unusual consumption.",
         "r": "Fleet managers need cost-per-mile data to justify EV transition. Faulty charger detection prevents revenue loss of $200-500/day per broken unit.", "sub": [("ConsumptionReport", 8), ("CostAnalysis", 8), ("HealthMonitoring", 8)]}
    ],
    "af": {
        "orderTotal": 12.50, "transactionValue": 12.50, "averageOrderValue": 18.00,
        "contractValue": 0, "annualRevenue": 45000000, "revenuePerCustomer": 600,
        "profitMargin": 15.0, "customerLifetimeValue": 5400, "lifetimeValue": 5400,
        "acquisitionCost": 25, "costPerAcquisition": 25, "conversionProbability": 0.88,
        "conversionRate": 88, "engagementScore": 75, "timeToConversion": 5,
        "sessionDuration": 35, "pageViews": 3, "purchaseFrequency": 48,
        "netPromoterScore": 38, "satisfactionRating": 3.8, "retentionProbability": 0.78,
        "processingTime": 0.25, "operationalCost": 3.50, "efficiencyRating": 85,
        "kWhDelivered": 42, "chargerUtilisation": 28,
        "channel": ["mobile_app", "plug_and_charge", "RFID_card", "contactless_pay", "fleet_portal"],
        "deviceType": ["mobile", "vehicle", "card", "terminal", "desktop"],
        "region": ["California US", "Norway", "Netherlands", "UK", "China"],
        "customerSegmentValue": ["private_driver", "fleet_operator", "ride_hail_driver", "destination_charging", "workplace_charging"],
        "loyaltyTier": ["Unlimited", "Plus", "Standard", "Pay-as-you-go", "Guest"],
        "segment": ["DC_fast", "Level2_AC", "destination", "workplace", "residential"],
        "Productname": ["350kW Ultra-Fast Session", "22kW Destination Charge", "7kW Workplace Charge", "V2G Bidirectional Session", "Fleet Depot Charge"],
        "ProductId": ["EV-DC-001", "EV-L2-002", "EV-WP-003", "EV-V2-004", "EV-FL-005"],
        "ProductType": ["DC_fast", "AC_Level2", "workplace", "V2G", "fleet_depot"],
        "Price": [18.50, 8.00, 4.50, -2.00, 12.00],
        "chargingSpeed": [350, 22, 7, 11, 150],
        "sessionDurationMin": [20, 240, 480, 300, 60],
        "marketTrend": ["ultra_fast_charging", "V2G_grid_services", "autonomous_charging", "battery_swapping", "solar_canopy_charging"]
    }
},
"config-ev-fleet-charging.json": {
    "co": "ChargePoint Plus", "dom": "https://www.chargepointplus.com",
    "ind": "Electric Vehicle & Charging", "jt": "Fleet Charging",
    "jd": "AI-Managed EV Fleet Charging Operations",
    "steps": [
        {"sn": "FleetScheduling", "sv": "FleetScheduleService", "c": "Planning", "dur": 1,
         "d": "AI schedules when each fleet vehicle charges based on next-day routes, energy requirements, grid tariffs, and charger availability. Overnight depot charging optimised.",
         "r": "Unmanaged fleet charging causes grid demand spikes that trigger demand charges ($10K-50K/month). Smart scheduling cuts energy costs by 30-50%.", "sub": [("RouteEnergyCalc", 0.3), ("TariffOptimization", 0.3), ("ChargerAllocation", 0.4)]},
        {"sn": "DemandManagement", "sv": "DemandManageService", "c": "Energy", "dur": 8,
         "d": "AI manages total site power draw to stay within grid connection capacity. Load balancing across chargers. Demand response participation for grid incentive revenue.",
         "r": "Grid connection upgrades cost $500K-5M and take 12-24 months. Load management enables 2x more vehicles on existing infrastructure.", "sub": [("LoadBalancing", 3), ("PeakShaving", 3), ("DemandResponse", 2)]},
        {"sn": "ChargingExecution", "sv": "ChargingExecService", "c": "Operations", "dur": 480,
         "d": "AI monitors all charging sessions: power delivery, battery health, fault detection, and completion status. Automatic failover to alternative chargers on fault.",
         "r": "A vehicle that fails to charge overnight misses its next-day route, requiring a diesel substitute costing $300-500/day in fuel and emissions penalties.", "sub": [("SessionMonitoring", 160), ("FaultDetection", 160), ("FailoverManagement", 160)]},
        {"sn": "EnergyProcurement", "sv": "EnergyProcureService", "c": "Procurement", "dur": 24,
         "d": "AI optimises energy procurement: spot market, PPA, on-site solar, and battery storage dispatch. Carbon matching ensures 100% renewable charging for ESG compliance.",
         "r": "Energy cost is 60-70% of fleet charging opex. Optimal procurement saves 15-25% vs standard tariffs. Green energy matching is required for fleet ESG claims.", "sub": [("SpotMarketTrading", 8), ("PPAManagement", 8), ("SolarStorageDispatch", 8)]},
        {"sn": "VehicleHealthTracking", "sv": "VehicleHealthService", "c": "Maintenance", "dur": 168,
         "d": "AI analyses battery degradation from charging patterns. State of health (SoH) tracked per vehicle. Charging strategies adjusted to extend battery warranty life.",
         "r": "Battery replacement costs $15K-40K per vehicle. Optimal charging strategies extend battery life by 20-30%, saving $5K-12K per vehicle over its lifecycle.", "sub": [("SoHTracking", 56), ("DegradationAnalysis", 56), ("ChargingAdjustment", 56)]},
        {"sn": "TCOReporting", "sv": "TCOReportService", "c": "Analytics", "dur": 24,
         "d": "AI calculates total cost of ownership vs diesel fleet. Energy cost per mile, maintenance savings, and carbon reduction quantified. Board-level transition business case updated.",
         "r": "TCO analysis justifies continued EV fleet expansion to the board. Most fleets achieve EV TCO parity at year 3 and 20-30% saving by year 5.", "sub": [("CostPerMile", 8), ("MaintenanceSavings", 8), ("CarbonReduction", 8)]}
    ],
    "af": {
        "orderTotal": 2500, "transactionValue": 2500, "averageOrderValue": 8500,
        "contractValue": 500000, "annualRevenue": 45000000, "revenuePerCustomer": 120000,
        "profitMargin": 18.0, "customerLifetimeValue": 900000, "lifetimeValue": 900000,
        "acquisitionCost": 15000, "costPerAcquisition": 15000, "conversionProbability": 0.72,
        "conversionRate": 72, "engagementScore": 82, "timeToConversion": 4320,
        "sessionDuration": 1800, "pageViews": 12, "purchaseFrequency": 365,
        "netPromoterScore": 48, "satisfactionRating": 4.2, "retentionProbability": 0.90,
        "processingTime": 480, "operationalCost": 800, "efficiencyRating": 82,
        "fleetSize": 250, "avgDailyMiles": 120,
        "channel": ["fleet_portal", "depot_terminal", "mobile_driver_app", "API_telematics", "energy_dashboard"],
        "deviceType": ["desktop", "kiosk", "mobile", "server", "desktop"],
        "region": ["London UK", "Amsterdam NL", "LA US", "Sydney AU", "Oslo NO"],
        "customerSegmentValue": ["delivery_fleet", "bus_operator", "municipal_fleet", "corporate_fleet", "taxi_operator"],
        "loyaltyTier": ["Enterprise", "Growth", "Standard", "Trial", "Pilot"],
        "segment": ["depot_overnight", "opportunity_fast", "route_planned", "return_to_base", "mixed_use"],
        "Productname": ["Depot Smart Charging", "Route-Optimised Charging Plan", "V2G Fleet Revenue", "Solar+Battery Depot", "Fleet Energy Dashboard"],
        "ProductId": ["EV-DP-001", "EV-RT-002", "EV-VG-003", "EV-SB-004", "EV-FD-005"],
        "ProductType": ["depot_charging", "route_planning", "V2G", "solar_storage", "analytics"],
        "Price": [500000, 120000, 80000, 350000, 50000],
        "energyCostPerMile": [0.04, 0.06, 0.03, 0.02, 0],
        "emissionsSavedTonnes": [450, 180, 90, 620, 0],
        "marketTrend": ["fleet_electrification", "depot_smart_charging", "V2G_revenue", "battery_second_life", "charging_as_a_service"]
    }
},
"config-fashion-personal-styling.json": {
    "co": "StyleAI Fashion", "dom": "https://www.styleai-fashion.com",
    "ind": "Fashion & Apparel", "jt": "Personal Styling",
    "jd": "AI-Powered Personal Fashion Styling",
    "steps": [
        {"sn": "StyleProfiling", "sv": "StyleProfileService", "c": "Onboarding", "dur": 5,
         "d": "AI builds style profile from quiz, body measurements, colour analysis, lifestyle, and budget preferences. Computer vision analyses wardrobe photos to understand existing style.",
         "r": "Accurate style profiling improves first-box satisfaction from 40% to 75%. Poor profiling causes returns and churn.", "sub": [("QuizAnalysis", 2), ("BodyAnalysis", 1.5), ("WardrobeScanning", 1.5)]},
        {"sn": "TrendMatching", "sv": "TrendMatchService", "c": "Curation", "dur": 2,
         "d": "AI matches client profile to current trends, seasonal collections, and curated looks. Personal stylist preferences layered on top of algorithmic suggestions.",
         "r": "Trend-aligned suggestions drive 30% higher keep rates. Clients want to feel current but within their comfort zone.", "sub": [("TrendAnalysis", 0.8), ("CollectionMatching", 0.6), ("StylistOverlay", 0.6)]},
        {"sn": "OutfitAssembly", "sv": "OutfitService", "c": "Styling", "dur": 3,
         "d": "AI assembles complete outfits considering colour theory, pattern mixing, proportion, and occasion. Mix-and-match compatibility with existing wardrobe items.",
         "r": "Complete outfit suggestions generate 50% higher basket value than item-by-item browsing. Cross-selling through outfit assembly drives $25-40 incremental AOV.", "sub": [("OutfitGeneration", 1), ("ColourHarmony", 1), ("WardrobeIntegration", 1)]},
        {"sn": "VirtualFitting", "sv": "VirtualFitService", "c": "Experience", "dur": 1,
         "d": "AI virtual try-on with body-accurate avatar. Size recommendation using brand-specific fit models. Fabric drape simulation for visual confidence.",
         "r": "Virtual fitting reduces returns by 25-40%. Size recommendation accuracy above 85% is the industry threshold for profitability.", "sub": [("AvatarRendering", 0.4), ("SizeRecommendation", 0.3), ("FabricSimulation", 0.3)]},
        {"sn": "BoxFulfilment", "sv": "BoxFulfilmentService", "c": "Delivery", "dur": 48,
         "d": "Curated styling box picked, packed, and shipped. Personal note from stylist included. Easy return process for items that don't work.",
         "r": "Speed to delivery after order is a satisfaction driver. Styling box customers have 3x higher LTV than browse-and-buy customers.", "sub": [("Picking", 16), ("PersonalTouch", 8), ("Shipping", 24)]},
        {"sn": "FeedbackLoop", "sv": "FeedbackService", "c": "Learning", "dur": 5,
         "d": "AI captures keep/return decisions, fit feedback, and style preference updates. Each interaction improves future recommendations. Stylist notes incorporated.",
         "r": "The feedback loop is the moat. Each cycle improves keep rate by 2-3%. After 5 boxes, keep rate reaches 70%+, making unit economics highly profitable.", "sub": [("KeepReturnCapture", 1), ("FitFeedbackAnalysis", 2), ("ProfileRefinement", 2)]}
    ],
    "af": {
        "orderTotal": 285, "transactionValue": 285, "averageOrderValue": 250,
        "contractValue": 0, "annualRevenue": 120000000, "revenuePerCustomer": 1200,
        "profitMargin": 45.0, "customerLifetimeValue": 4800, "lifetimeValue": 4800,
        "acquisitionCost": 65, "costPerAcquisition": 65, "conversionProbability": 0.18,
        "conversionRate": 18, "engagementScore": 85, "timeToConversion": 720,
        "sessionDuration": 900, "pageViews": 15, "purchaseFrequency": 8,
        "netPromoterScore": 58, "satisfactionRating": 4.4, "retentionProbability": 0.68,
        "processingTime": 2880, "operationalCost": 45, "efficiencyRating": 78,
        "keepRate": 62, "returnRate": 38,
        "channel": ["mobile_app", "website", "instagram_shop", "stylist_chat", "subscription_box"],
        "deviceType": ["mobile", "desktop", "mobile", "mobile", "desktop"],
        "region": ["US", "UK", "France", "Japan", "Australia"],
        "customerSegmentValue": ["professional_woman", "casual_dresser", "trend_seeker", "minimalist", "occasion_shopper"],
        "loyaltyTier": ["Style VIP", "Insider", "Explorer", "Basic", "Trial"],
        "segment": ["workwear", "casual", "evening", "activewear", "accessories"],
        "Productname": ["Tailored Blazer", "Silk Midi Dress", "Cashmere Knit", "Leather Ankle Boot", "Statement Earrings"],
        "ProductId": ["FSH-BL-001", "FSH-DR-002", "FSH-KN-003", "FSH-BT-004", "FSH-AC-005"],
        "ProductType": ["jacket", "dress", "knitwear", "footwear", "accessory"],
        "Price": [195, 165, 145, 225, 85],
        "sizeAccuracy": [0.88, 0.85, 0.82, 0.90, 0.95],
        "fabricComposition": ["wool_blend", "100%_silk", "cashmere_blend", "leather", "gold_plate"],
        "marketTrend": ["AI_styling", "rental_fashion", "capsule_wardrobe", "sustainable_fashion", "resale_integration"]
    }
},
"config-fashion-trend-forecasting.json": {
    "co": "StyleAI Fashion", "dom": "https://www.styleai-fashion.com",
    "ind": "Fashion & Apparel", "jt": "Trend Forecasting",
    "jd": "AI-Driven Fashion Trend Prediction & Merchandising",
    "steps": [
        {"sn": "SignalDetection", "sv": "SignalDetectionService", "c": "Intelligence", "dur": 168,
         "d": "AI monitors runway shows, street style, social media, search trends, and cultural shifts. Natural language processing identifies emerging theme clusters 6-12 months ahead.",
         "r": "Trend detection 6 months early enables design lead time. Brands that lead trends achieve 3-5x sell-through vs followers.", "sub": [("RunwayAnalysis", 40), ("SocialListening", 64), ("SearchTrending", 64)]},
        {"sn": "TrendValidation", "sv": "ValidationService", "c": "Analysis", "dur": 72,
         "d": "AI validates trend signals against historical adoption curves. Differentiates fads from sustainable trends. Market sizing per trend for different customer segments.",
         "r": "Investing in fads wastes design and production budget. Validated trends have 80% chance of commercial success vs 25% for unvalidated.", "sub": [("AdoptionModelling", 24), ("FadFiltering", 24), ("MarketSizing", 24)]},
        {"sn": "AssortmentPlanning", "sv": "AssortmentService", "c": "Merchandising", "dur": 168,
         "d": "AI translates trend insights into buy plans: SKU count, colour palette, size curve, and price architecture. Regional demand differences factored in.",
         "r": "Optimal assortment drives full-price sell-through from 55% to 75%. Over-buying causes markdowns that erode margin by 15-25%.", "sub": [("SKUPlanning", 56), ("ColourPalette", 56), ("SizeCurveOptimization", 56)]},
        {"sn": "DemandForecasting", "sv": "DemandForecastService", "c": "Planning", "dur": 48,
         "d": "AI predicts demand per SKU by store and channel. Weather adjustments, event calendars, and promotional uplift factored in. Safety stock calculated.",
         "r": "Demand forecast accuracy directly affects markdowns and stockouts. 5% accuracy improvement = 2% margin improvement on a $100M brand.", "sub": [("ChannelForecasting", 16), ("WeatherAdjustment", 16), ("SafetyStockCalc", 16)]},
        {"sn": "PricingOptimization", "sv": "PricingService", "c": "Revenue", "dur": 24,
         "d": "AI sets initial prices, plans markdown cadence, and manages promotional pricing. Competitor price monitoring. Price elasticity modelled per product category.",
         "r": "Dynamic pricing improves margin by 3-8%. Markdown optimization prevents leaving money on the table while clearing inventory.", "sub": [("InitialPricing", 8), ("MarkdownPlanning", 8), ("CompetitorMonitoring", 8)]},
        {"sn": "SeasonReview", "sv": "ReviewService", "c": "Analytics", "dur": 48,
         "d": "AI evaluates forecast vs actual performance per trend, category, and store. Lessons learned fed into next season buying. Winner/loser analysis drives repeat or exit decisions.",
         "r": "Season review is how buying teams learn. Brands that systematically review improve buy accuracy by 5% per season, compounding over time.", "sub": [("PerformanceAnalysis", 16), ("LessonsLearned", 16), ("NextSeasonRecommendations", 16)]}
    ],
    "af": {
        "orderTotal": 85, "transactionValue": 85, "averageOrderValue": 110,
        "contractValue": 0, "annualRevenue": 120000000, "revenuePerCustomer": 450,
        "profitMargin": 58.0, "customerLifetimeValue": 2200, "lifetimeValue": 2200,
        "acquisitionCost": 35, "costPerAcquisition": 35, "conversionProbability": 0.08,
        "conversionRate": 8, "engagementScore": 72, "timeToConversion": 1440,
        "sessionDuration": 600, "pageViews": 12, "purchaseFrequency": 5,
        "netPromoterScore": 45, "satisfactionRating": 4.0, "retentionProbability": 0.55,
        "processingTime": 10080, "operationalCost": 22, "efficiencyRating": 75,
        "fullPriceSellThrough": 68, "markdownRate": 32,
        "channel": ["ecommerce", "flagship_store", "wholesale", "outlet", "marketplace"],
        "deviceType": ["mobile", "kiosk", "desktop", "desktop", "mobile"],
        "region": ["US", "EU", "Japan", "China", "Middle East"],
        "customerSegmentValue": ["fashion_forward", "classic_buyer", "value_hunter", "luxury_aspirant", "gen_z_native"],
        "loyaltyTier": ["VIP", "Insider", "Member", "Basic", "New"],
        "segment": ["womenswear", "menswear", "accessories", "footwear", "denim"],
        "Productname": ["AW26 Oversized Coat", "Resort Linen Blazer", "Chunky Platform Boot", "Leather Bucket Bag", "Wide-Leg Jean"],
        "ProductId": ["FSH-CT-001", "FSH-BZ-002", "FSH-BT-003", "FSH-BG-004", "FSH-DN-005"],
        "ProductType": ["outerwear", "blazer", "footwear", "bag", "denim"],
        "Price": [325, 195, 185, 275, 125],
        "sellThroughRate": [0.72, 0.68, 0.80, 0.75, 0.65],
        "trendStrength": ["strong", "emerging", "peak", "mature", "emerging"],
        "marketTrend": ["AI_trend_prediction", "real_time_demand_sensing", "circular_fashion", "hyper_personalization", "social_commerce"]
    }
},
"config-fitness-member-retention.json": {
    "co": "FitTech Wellness", "dom": "https://www.fittech-wellness.com",
    "ind": "Fitness & Wellness", "jt": "Member Retention",
    "jd": "AI-Powered Gym Member Retention Programme",
    "steps": [
        {"sn": "ChurnPrediction", "sv": "ChurnPredictionService", "c": "Prediction", "dur": 24,
         "d": "AI predicts churn probability for each member based on visit frequency decline, class booking changes, payment issues, and engagement patterns. 30/60/90-day churn risk scored.",
         "r": "Acquiring a new gym member costs 5-8x more than retaining one. Identifying at-risk members 30 days before churn enables intervention.", "sub": [("VisitAnalysis", 8), ("EngagementScoring", 8), ("RiskClassification", 8)]},
        {"sn": "PersonalisedIntervention", "sv": "InterventionService", "c": "Action", "dur": 1,
         "d": "AI selects optimal retention intervention per member: personal trainer session, class recommendation, friend referral incentive, or membership pause offer.",
         "r": "Personalised interventions convert 35% of at-risk members back to active vs 8% for generic communications. One-size-fits-all fails.", "sub": [("InterventionSelection", 0.3), ("OfferGeneration", 0.3), ("ChannelOptimization", 0.4)]},
        {"sn": "EngagementOptimization", "sv": "EngagementService", "c": "Engagement", "dur": 720,
         "d": "AI optimises workout plans, class schedules, and social connections. Gamification challenges, progress milestones, and community features drive habitual attendance.",
         "r": "Members who attend 3+x/week have 90% retention vs 40% for 1x/week. AI-optimised engagement increases average visits by 1.5x.", "sub": [("WorkoutPersonalisation", 240), ("ClassRecommendation", 240), ("GamificationChallenges", 240)]},
        {"sn": "ProgressTracking", "sv": "ProgressService", "c": "Motivation", "dur": 168,
         "d": "AI tracks fitness progress: body composition, strength gains, cardiovascular improvement, and goal attainment. Visual progress reports and AI coaching feedback.",
         "r": "Members who see measurable progress have 3x higher retention. Without progress visibility, 60% of gym members quit within 3 months.", "sub": [("BodyComposition", 56), ("StrengthTracking", 56), ("GoalTracking", 56)]},
        {"sn": "CommunityBuilding", "sv": "CommunityService", "c": "Social", "dur": 720,
         "d": "AI connects members with similar goals, fitness levels, and schedules. Group challenges, buddy matching, and social leaderboards. Event and class social features.",
         "r": "Social connection is the strongest retention predictor after visit frequency. Members with a gym buddy have 80% 12-month retention vs 55% solo.", "sub": [("BuddyMatching", 240), ("GroupChallenges", 240), ("SocialFeatures", 240)]},
        {"sn": "RetentionAnalytics", "sv": "RetentionAnalyticsService", "c": "Analytics", "dur": 24,
         "d": "AI analyses retention rates by segment, location, membership type, and intervention type. Revenue impact of retention programmes quantified. Churn reasons categorised.",
         "r": "Understanding why members leave enables systemic improvement. A 5% improvement in retention equals 25-35% profit increase for most gyms.", "sub": [("SegmentAnalysis", 8), ("InterventionROI", 8), ("ChurnReasonMapping", 8)]}
    ],
    "af": {
        "orderTotal": 49.99, "transactionValue": 49.99, "averageOrderValue": 65,
        "contractValue": 600, "annualRevenue": 18000000, "revenuePerCustomer": 720,
        "profitMargin": 35.0, "customerLifetimeValue": 2400, "lifetimeValue": 2400,
        "acquisitionCost": 85, "costPerAcquisition": 85, "conversionProbability": 0.15,
        "conversionRate": 15, "engagementScore": 68, "timeToConversion": 2160,
        "sessionDuration": 3600, "pageViews": 5, "purchaseFrequency": 12,
        "netPromoterScore": 42, "satisfactionRating": 4.0, "retentionProbability": 0.72,
        "processingTime": 300, "operationalCost": 15, "efficiencyRating": 75,
        "monthlyVisits": 8.5, "churnRate": 4.2,
        "channel": ["mobile_app", "front_desk", "website", "social_media", "referral"],
        "deviceType": ["mobile", "kiosk", "desktop", "mobile", "mobile"],
        "region": ["London", "New York", "LA", "Sydney", "Dubai"],
        "customerSegmentValue": ["committed_athlete", "casual_goer", "new_year_joiner", "class_junkie", "personal_training"],
        "loyaltyTier": ["Platinum", "Gold", "Silver", "Bronze", "Trial"],
        "segment": ["gym_floor", "group_classes", "personal_training", "swimming", "spa_wellness"],
        "Productname": ["Unlimited Gym Membership", "Class Pass Bundle", "PT Session Pack (10)", "Wellness Recovery Add-on", "Corporate Group Plan"],
        "ProductId": ["FIT-GM-001", "FIT-CP-002", "FIT-PT-003", "FIT-WR-004", "FIT-CG-005"],
        "ProductType": ["membership", "class_pass", "personal_training", "add_on", "corporate"],
        "Price": [49.99, 79.99, 350, 25, 39.99],
        "avgVisitsPerWeek": [3.2, 2.8, 2.0, 1.5, 1.8],
        "retentionAt12Months": [0.72, 0.65, 0.80, 0.55, 0.68],
        "marketTrend": ["AI_personal_training", "wearable_integration", "hybrid_digital_gym", "recovery_wellness", "corporate_wellness"]
    }
},
"config-fitness-class-scheduling.json": {
    "co": "FitTech Wellness", "dom": "https://www.fittech-wellness.com",
    "ind": "Fitness & Wellness", "jt": "Class Scheduling",
    "jd": "AI-Optimised Fitness Class Scheduling",
    "steps": [
        {"sn": "DemandPrediction", "sv": "DemandPredictService", "c": "Forecasting", "dur": 24,
         "d": "AI predicts class demand by type, time slot, instructor, and day of week. Seasonal trends, weather impact, and local events factored into forecasts.",
         "r": "Optimal class size maximises revenue per studio hour. Under-scheduled popular classes lose revenue; over-scheduled empty classes waste instructor costs.", "sub": [("HistoricalAnalysis", 8), ("SeasonalAdjustment", 8), ("EventImpact", 8)]},
        {"sn": "TimetableOptimization", "sv": "TimetableService", "c": "Planning", "dur": 4,
         "d": "AI generates weekly timetable balancing member preferences, instructor availability, studio capacity, and equipment requirements. Avoids scheduling conflicts.",
         "r": "Optimised timetabling improves class utilisation from 65% to 85%. Each additional participant in a class generates pure margin.", "sub": [("SlotOptimization", 1.5), ("InstructorMatching", 1.5), ("CapacityBalancing", 1)]},
        {"sn": "InstructorManagement", "sv": "InstructorService", "c": "Staffing", "dur": 8,
         "d": "AI manages instructor schedules, substitution pool, and performance ratings. Popular instructors assigned to prime slots. Emerging talent identified from member feedback.",
         "r": "Top instructors drive 40% higher class attendance. Poor scheduling causes instructor burnout and turnover, which costs $5K-10K per replacement.", "sub": [("ScheduleOptimization", 3), ("SubstitutionPool", 2), ("PerformanceTracking", 3)]},
        {"sn": "BookingManagement", "sv": "BookingService", "c": "Operations", "dur": 168,
         "d": "AI manages class bookings, waitlists, no-show prediction, and last-minute availability. Dynamic pricing for peak classes. Reminder notifications reduce no-shows.",
         "r": "No-shows waste 15-20% of capacity. AI-powered reminders and waitlist management reduce no-shows from 20% to 8%.", "sub": [("BookingEngine", 56), ("WaitlistManagement", 56), ("NoShowPrediction", 56)]},
        {"sn": "InClassExperience", "sv": "InClassService", "c": "Experience", "dur": 1,
         "d": "Connected class experience: heart rate tracking, performance leaderboard, music sync, and effort-based difficulty adjustment. Post-class summary and personalised recommendations.",
         "r": "Connected class experiences increase rebooking by 35%. Heart rate-based training ensures members get results, which drives retention.", "sub": [("HeartRateTracking", 0.3), ("PerformanceDisplay", 0.3), ("PostClassSummary", 0.4)]},
        {"sn": "ClassPerformanceAnalytics", "sv": "ClassAnalyticsService", "c": "Analytics", "dur": 24,
         "d": "AI analyses class performance: attendance trends, member satisfaction, instructor ratings, and revenue per studio hour. New class format testing with A/B methodology.",
         "r": "Data-driven class programming improves revenue per studio hour by 15-25%. Replacing underperforming formats with proven ones compounds growth.", "sub": [("AttendanceTrends", 8), ("SatisfactionAnalysis", 8), ("RevenueOptimization", 8)]}
    ],
    "af": {
        "orderTotal": 15, "transactionValue": 15, "averageOrderValue": 18,
        "contractValue": 0, "annualRevenue": 18000000, "revenuePerCustomer": 720,
        "profitMargin": 40.0, "customerLifetimeValue": 2400, "lifetimeValue": 2400,
        "acquisitionCost": 45, "costPerAcquisition": 45, "conversionProbability": 0.35,
        "conversionRate": 35, "engagementScore": 82, "timeToConversion": 60,
        "sessionDuration": 2700, "pageViews": 4, "purchaseFrequency": 48,
        "netPromoterScore": 55, "satisfactionRating": 4.4, "retentionProbability": 0.78,
        "processingTime": 15, "operationalCost": 6, "efficiencyRating": 82,
        "classUtilisation": 78, "noShowRate": 12,
        "channel": ["mobile_app", "reception_kiosk", "website", "instagram", "classpass"],
        "deviceType": ["mobile", "kiosk", "desktop", "mobile", "mobile"],
        "region": ["London", "New York", "LA", "Melbourne", "Berlin"],
        "customerSegmentValue": ["class_regular", "drop_in", "unlimited_member", "classpass_user", "corporate_wellness"],
        "loyaltyTier": ["Unlimited", "10-Pack", "5-Pack", "Drop-In", "Trial"],
        "segment": ["HIIT", "yoga", "spin", "strength", "pilates"],
        "Productname": ["HIIT Express 30", "Vinyasa Flow 60", "Spin & Burn 45", "Strength Lab 50", "Reformer Pilates 55"],
        "ProductId": ["CLS-HT-001", "CLS-YG-002", "CLS-SP-003", "CLS-ST-004", "CLS-PL-005"],
        "ProductType": ["HIIT", "yoga", "cycling", "strength", "pilates"],
        "Price": [15, 18, 15, 15, 25],
        "avgClassSize": [22, 18, 35, 16, 12],
        "instructorRating": [4.7, 4.8, 4.5, 4.6, 4.9],
        "marketTrend": ["boutique_fitness", "connected_class", "hybrid_streaming", "recovery_classes", "outdoor_fitness"]
    }
},
}

if __name__ == "__main__":
    for fn, data in SECTORS.items():
        gen(fn, data)
    print(f"Batch 4 complete: {len(SECTORS)} configs updated.")
